// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repositories/gcs/gcs.go
//
// Generated by this command:
//
//	mockgen -source=./internal/repositories/gcs/gcs.go -destination=./internal/repositories/gcs/mock/gcs_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	io "io"
	reflect "reflect"
	time "time"

	models "bitbucket.org/Amartha/go-accounting/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockCloudStorageRepository is a mock of CloudStorageRepository interface.
type MockCloudStorageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCloudStorageRepositoryMockRecorder
	isgomock struct{}
}

// MockCloudStorageRepositoryMockRecorder is the mock recorder for MockCloudStorageRepository.
type MockCloudStorageRepositoryMockRecorder struct {
	mock *MockCloudStorageRepository
}

// NewMockCloudStorageRepository creates a new mock instance.
func NewMockCloudStorageRepository(ctrl *gomock.Controller) *MockCloudStorageRepository {
	mock := &MockCloudStorageRepository{ctrl: ctrl}
	mock.recorder = &MockCloudStorageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCloudStorageRepository) EXPECT() *MockCloudStorageRepositoryMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockCloudStorageRepository) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockCloudStorageRepositoryMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockCloudStorageRepository)(nil).Close))
}

// FileExists mocks base method.
func (m *MockCloudStorageRepository) FileExists(ctx context.Context, payload *models.CloudStoragePayload) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileExists", ctx, payload)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FileExists indicates an expected call of FileExists.
func (mr *MockCloudStorageRepositoryMockRecorder) FileExists(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileExists", reflect.TypeOf((*MockCloudStorageRepository)(nil).FileExists), ctx, payload)
}

// GetSignedURL mocks base method.
func (m *MockCloudStorageRepository) GetSignedURL(payload models.CloudStoragePayload, expireDuration time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSignedURL", payload, expireDuration)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSignedURL indicates an expected call of GetSignedURL.
func (mr *MockCloudStorageRepositoryMockRecorder) GetSignedURL(payload, expireDuration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSignedURL", reflect.TypeOf((*MockCloudStorageRepository)(nil).GetSignedURL), payload, expireDuration)
}

// ListFiles mocks base method.
func (m *MockCloudStorageRepository) ListFiles(ctx context.Context, payload *models.CloudStoragePayload) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFiles", ctx, payload)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFiles indicates an expected call of ListFiles.
func (mr *MockCloudStorageRepositoryMockRecorder) ListFiles(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFiles", reflect.TypeOf((*MockCloudStorageRepository)(nil).ListFiles), ctx, payload)
}

// NewReader mocks base method.
func (m *MockCloudStorageRepository) NewReader(ctx context.Context, payload *models.CloudStoragePayload) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewReader", ctx, payload)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewReader indicates an expected call of NewReader.
func (mr *MockCloudStorageRepositoryMockRecorder) NewReader(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewReader", reflect.TypeOf((*MockCloudStorageRepository)(nil).NewReader), ctx, payload)
}

// NewWriter mocks base method.
func (m *MockCloudStorageRepository) NewWriter(ctx context.Context, payload *models.CloudStoragePayload) io.WriteCloser {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewWriter", ctx, payload)
	ret0, _ := ret[0].(io.WriteCloser)
	return ret0
}

// NewWriter indicates an expected call of NewWriter.
func (mr *MockCloudStorageRepositoryMockRecorder) NewWriter(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewWriter", reflect.TypeOf((*MockCloudStorageRepository)(nil).NewWriter), ctx, payload)
}
