// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repositories/bq/bq.go
//
// Generated by this command:
//
//	mockgen -source=./internal/repositories/bq/bq.go -destination=./internal/repositories/bq/mock/bq_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	models "bitbucket.org/Amartha/go-accounting/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockBigQueryRepository is a mock of BigQueryRepository interface.
type MockBigQueryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBigQueryRepositoryMockRecorder
	isgomock struct{}
}

// MockBigQueryRepositoryMockRecorder is the mock recorder for MockBigQueryRepository.
type MockBigQueryRepositoryMockRecorder struct {
	mock *MockBigQueryRepository
}

// NewMockBigQueryRepository creates a new mock instance.
func NewMockBigQueryRepository(ctrl *gomock.Controller) *MockBigQueryRepository {
	mock := &MockBigQueryRepository{ctrl: ctrl}
	mock.recorder = &MockBigQueryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBigQueryRepository) EXPECT() *MockBigQueryRepositoryMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockBigQueryRepository) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockBigQueryRepositoryMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockBigQueryRepository)(nil).Close))
}

// ExportTrialBalanceDetail mocks base method.
func (m *MockBigQueryRepository) ExportTrialBalanceDetail(ctx context.Context, entityCodes []string, baseDate string, date time.Time, subCategories *[]models.SubCategory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportTrialBalanceDetail", ctx, entityCodes, baseDate, date, subCategories)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExportTrialBalanceDetail indicates an expected call of ExportTrialBalanceDetail.
func (mr *MockBigQueryRepositoryMockRecorder) ExportTrialBalanceDetail(ctx, entityCodes, baseDate, date, subCategories any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportTrialBalanceDetail", reflect.TypeOf((*MockBigQueryRepository)(nil).ExportTrialBalanceDetail), ctx, entityCodes, baseDate, date, subCategories)
}

// ExportTrialBalanceSummary mocks base method.
func (m *MockBigQueryRepository) ExportTrialBalanceSummary(ctx context.Context, entityCodes []string, baseDate string, date time.Time) ([]models.CreateTrialBalancePeriod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportTrialBalanceSummary", ctx, entityCodes, baseDate, date)
	ret0, _ := ret[0].([]models.CreateTrialBalancePeriod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExportTrialBalanceSummary indicates an expected call of ExportTrialBalanceSummary.
func (mr *MockBigQueryRepositoryMockRecorder) ExportTrialBalanceSummary(ctx, entityCodes, baseDate, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportTrialBalanceSummary", reflect.TypeOf((*MockBigQueryRepository)(nil).ExportTrialBalanceSummary), ctx, entityCodes, baseDate, date)
}

// QueryGenerateTrialBalanceDetail mocks base method.
func (m *MockBigQueryRepository) QueryGenerateTrialBalanceDetail(ctx context.Context, baseDate, previousMonth, periodStartEnd, startDate, endDate string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryGenerateTrialBalanceDetail", ctx, baseDate, previousMonth, periodStartEnd, startDate, endDate)
	ret0, _ := ret[0].(error)
	return ret0
}

// QueryGenerateTrialBalanceDetail indicates an expected call of QueryGenerateTrialBalanceDetail.
func (mr *MockBigQueryRepositoryMockRecorder) QueryGenerateTrialBalanceDetail(ctx, baseDate, previousMonth, periodStartEnd, startDate, endDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryGenerateTrialBalanceDetail", reflect.TypeOf((*MockBigQueryRepository)(nil).QueryGenerateTrialBalanceDetail), ctx, baseDate, previousMonth, periodStartEnd, startDate, endDate)
}

// QueryGenerateTrialBalanceSummary mocks base method.
func (m *MockBigQueryRepository) QueryGenerateTrialBalanceSummary(ctx context.Context, baseDate string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryGenerateTrialBalanceSummary", ctx, baseDate)
	ret0, _ := ret[0].(error)
	return ret0
}

// QueryGenerateTrialBalanceSummary indicates an expected call of QueryGenerateTrialBalanceSummary.
func (mr *MockBigQueryRepositoryMockRecorder) QueryGenerateTrialBalanceSummary(ctx, baseDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryGenerateTrialBalanceSummary", reflect.TypeOf((*MockBigQueryRepository)(nil).QueryGenerateTrialBalanceSummary), ctx, baseDate)
}

// QueryGetTransactions mocks base method.
func (m *MockBigQueryRepository) QueryGetTransactions(ctx context.Context, transactionIDs []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryGetTransactions", ctx, transactionIDs)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryGetTransactions indicates an expected call of QueryGetTransactions.
func (mr *MockBigQueryRepositoryMockRecorder) QueryGetTransactions(ctx, transactionIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryGetTransactions", reflect.TypeOf((*MockBigQueryRepository)(nil).QueryGetTransactions), ctx, transactionIDs)
}

// QueryInsertOpeningBalanceCreated mocks base method.
func (m *MockBigQueryRepository) QueryInsertOpeningBalanceCreated(ctx context.Context, sourceTable, entityCode string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryInsertOpeningBalanceCreated", ctx, sourceTable, entityCode)
	ret0, _ := ret[0].(error)
	return ret0
}

// QueryInsertOpeningBalanceCreated indicates an expected call of QueryInsertOpeningBalanceCreated.
func (mr *MockBigQueryRepositoryMockRecorder) QueryInsertOpeningBalanceCreated(ctx, sourceTable, entityCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryInsertOpeningBalanceCreated", reflect.TypeOf((*MockBigQueryRepository)(nil).QueryInsertOpeningBalanceCreated), ctx, sourceTable, entityCode)
}

// TableExists mocks base method.
func (m *MockBigQueryRepository) TableExists(ctx context.Context, baseDate string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TableExists", ctx, baseDate)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TableExists indicates an expected call of TableExists.
func (mr *MockBigQueryRepositoryMockRecorder) TableExists(ctx, baseDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TableExists", reflect.TypeOf((*MockBigQueryRepository)(nil).TableExists), ctx, baseDate)
}
