// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/pkg/file/file.go
//
// Generated by this command:
//
//	mockgen -source=./internal/pkg/file/file.go -destination=./internal/pkg/file/mock/file_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	csv "encoding/csv"
	io "io"
	os "os"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIOFile is a mock of IOFile interface.
type MockIOFile struct {
	ctrl     *gomock.Controller
	recorder *MockIOFileMockRecorder
	isgomock struct{}
}

// MockIOFileMockRecorder is the mock recorder for MockIOFile.
type MockIOFileMockRecorder struct {
	mock *MockIOFile
}

// NewMockIOFile creates a new mock instance.
func NewMockIOFile(ctrl *gomock.Controller) *MockIOFile {
	mock := &MockIOFile{ctrl: ctrl}
	mock.recorder = &MockIOFileMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIOFile) EXPECT() *MockIOFileMockRecorder {
	return m.recorder
}

// CSVProcessWrite mocks base method.
func (m *MockIOFile) CSVProcessWrite(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CSVProcessWrite", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CSVProcessWrite indicates an expected call of CSVProcessWrite.
func (mr *MockIOFileMockRecorder) CSVProcessWrite(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CSVProcessWrite", reflect.TypeOf((*MockIOFile)(nil).CSVProcessWrite), ctx)
}

// CSVReadAll mocks base method.
func (m *MockIOFile) CSVReadAll(fs io.Reader) ([][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CSVReadAll", fs)
	ret0, _ := ret[0].([][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CSVReadAll indicates an expected call of CSVReadAll.
func (mr *MockIOFileMockRecorder) CSVReadAll(fs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CSVReadAll", reflect.TypeOf((*MockIOFile)(nil).CSVReadAll), fs)
}

// CSVWriteAll mocks base method.
func (m *MockIOFile) CSVWriteAll(ctx context.Context, all [][]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CSVWriteAll", ctx, all)
	ret0, _ := ret[0].(error)
	return ret0
}

// CSVWriteAll indicates an expected call of CSVWriteAll.
func (mr *MockIOFileMockRecorder) CSVWriteAll(ctx, all any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CSVWriteAll", reflect.TypeOf((*MockIOFile)(nil).CSVWriteAll), ctx, all)
}

// CSVWriteBody mocks base method.
func (m *MockIOFile) CSVWriteBody(ctx context.Context, body []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CSVWriteBody", ctx, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// CSVWriteBody indicates an expected call of CSVWriteBody.
func (mr *MockIOFileMockRecorder) CSVWriteBody(ctx, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CSVWriteBody", reflect.TypeOf((*MockIOFile)(nil).CSVWriteBody), ctx, body)
}

// CSVWriteHeader mocks base method.
func (m *MockIOFile) CSVWriteHeader(ctx context.Context, header []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CSVWriteHeader", ctx, header)
	ret0, _ := ret[0].(error)
	return ret0
}

// CSVWriteHeader indicates an expected call of CSVWriteHeader.
func (mr *MockIOFileMockRecorder) CSVWriteHeader(ctx, header any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CSVWriteHeader", reflect.TypeOf((*MockIOFile)(nil).CSVWriteHeader), ctx, header)
}

// CopyFile mocks base method.
func (m *MockIOFile) CopyFile(dst io.Writer, src io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyFile", dst, src)
	ret0, _ := ret[0].(error)
	return ret0
}

// CopyFile indicates an expected call of CopyFile.
func (mr *MockIOFileMockRecorder) CopyFile(dst, src any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyFile", reflect.TypeOf((*MockIOFile)(nil).CopyFile), dst, src)
}

// CreateFile mocks base method.
func (m *MockIOFile) CreateFile(path string) (*os.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFile", path)
	ret0, _ := ret[0].(*os.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFile indicates an expected call of CreateFile.
func (mr *MockIOFileMockRecorder) CreateFile(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFile", reflect.TypeOf((*MockIOFile)(nil).CreateFile), path)
}

// NewCSVWriter mocks base method.
func (m *MockIOFile) NewCSVWriter(w io.Writer) *csv.Writer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewCSVWriter", w)
	ret0, _ := ret[0].(*csv.Writer)
	return ret0
}

// NewCSVWriter indicates an expected call of NewCSVWriter.
func (mr *MockIOFileMockRecorder) NewCSVWriter(w any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewCSVWriter", reflect.TypeOf((*MockIOFile)(nil).NewCSVWriter), w)
}

// OpenFile mocks base method.
func (m *MockIOFile) OpenFile(path string) (*os.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenFile", path)
	ret0, _ := ret[0].(*os.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenFile indicates an expected call of OpenFile.
func (mr *MockIOFileMockRecorder) OpenFile(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenFile", reflect.TypeOf((*MockIOFile)(nil).OpenFile), path)
}

// ReadAll mocks base method.
func (m *MockIOFile) ReadAll(src io.Reader) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAll", src)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAll indicates an expected call of ReadAll.
func (mr *MockIOFileMockRecorder) ReadAll(src any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAll", reflect.TypeOf((*MockIOFile)(nil).ReadAll), src)
}

// RemoveFile mocks base method.
func (m *MockIOFile) RemoveFile(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFile", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFile indicates an expected call of RemoveFile.
func (mr *MockIOFileMockRecorder) RemoveFile(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFile", reflect.TypeOf((*MockIOFile)(nil).RemoveFile), path)
}
