// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/services/accounting_service.go
//
// Generated by this command:
//
//	mockgen -source=./internal/services/accounting_service.go -destination=./internal/services/mock/accounting_service_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	bytes "bytes"
	context "context"
	reflect "reflect"
	time "time"

	models "bitbucket.org/Amartha/go-accounting/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockAccountingService is a mock of AccountingService interface.
type MockAccountingService struct {
	ctrl     *gomock.Controller
	recorder *MockAccountingServiceMockRecorder
	isgomock struct{}
}

// MockAccountingServiceMockRecorder is the mock recorder for MockAccountingService.
type MockAccountingServiceMockRecorder struct {
	mock *MockAccountingService
}

// NewMockAccountingService creates a new mock instance.
func NewMockAccountingService(ctrl *gomock.Controller) *MockAccountingService {
	mock := &MockAccountingService{ctrl: ctrl}
	mock.recorder = &MockAccountingServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountingService) EXPECT() *MockAccountingServiceMockRecorder {
	return m.recorder
}

// DownloadCSVGetBalanceSheet mocks base method.
func (m *MockAccountingService) DownloadCSVGetBalanceSheet(ctx context.Context, opts models.BalanceSheetFilterOptions, resp models.GetBalanceSheetResponse) (*bytes.Buffer, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadCSVGetBalanceSheet", ctx, opts, resp)
	ret0, _ := ret[0].(*bytes.Buffer)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DownloadCSVGetBalanceSheet indicates an expected call of DownloadCSVGetBalanceSheet.
func (mr *MockAccountingServiceMockRecorder) DownloadCSVGetBalanceSheet(ctx, opts, resp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadCSVGetBalanceSheet", reflect.TypeOf((*MockAccountingService)(nil).DownloadCSVGetBalanceSheet), ctx, opts, resp)
}

// DownloadSubLedgerCSV mocks base method.
func (m *MockAccountingService) DownloadSubLedgerCSV(ctx context.Context, opts models.SubLedgerFilterOptions) (*bytes.Buffer, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadSubLedgerCSV", ctx, opts)
	ret0, _ := ret[0].(*bytes.Buffer)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DownloadSubLedgerCSV indicates an expected call of DownloadSubLedgerCSV.
func (mr *MockAccountingServiceMockRecorder) DownloadSubLedgerCSV(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadSubLedgerCSV", reflect.TypeOf((*MockAccountingService)(nil).DownloadSubLedgerCSV), ctx, opts)
}

// DownloadTrialBalance mocks base method.
func (m *MockAccountingService) DownloadTrialBalance(ctx context.Context, opts models.TrialBalanceFilterOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadTrialBalance", ctx, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// DownloadTrialBalance indicates an expected call of DownloadTrialBalance.
func (mr *MockAccountingServiceMockRecorder) DownloadTrialBalance(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadTrialBalance", reflect.TypeOf((*MockAccountingService)(nil).DownloadTrialBalance), ctx, opts)
}

// GenerateAccountDailyBalance mocks base method.
func (m *MockAccountingService) GenerateAccountDailyBalance(ctx context.Context, date time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAccountDailyBalance", ctx, date)
	ret0, _ := ret[0].(error)
	return ret0
}

// GenerateAccountDailyBalance indicates an expected call of GenerateAccountDailyBalance.
func (mr *MockAccountingServiceMockRecorder) GenerateAccountDailyBalance(ctx, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAccountDailyBalance", reflect.TypeOf((*MockAccountingService)(nil).GenerateAccountDailyBalance), ctx, date)
}

// GenerateAccountTrialBalanceDaily mocks base method.
func (m *MockAccountingService) GenerateAccountTrialBalanceDaily(ctx context.Context, date time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAccountTrialBalanceDaily", ctx, date)
	ret0, _ := ret[0].(error)
	return ret0
}

// GenerateAccountTrialBalanceDaily indicates an expected call of GenerateAccountTrialBalanceDaily.
func (mr *MockAccountingServiceMockRecorder) GenerateAccountTrialBalanceDaily(ctx, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAccountTrialBalanceDaily", reflect.TypeOf((*MockAccountingService)(nil).GenerateAccountTrialBalanceDaily), ctx, date)
}

// GenerateAdjustmentTrialBalanceBigQuery mocks base method.
func (m *MockAccountingService) GenerateAdjustmentTrialBalanceBigQuery(ctx context.Context, in models.AdjustmentTrialBalanceFilter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAdjustmentTrialBalanceBigQuery", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// GenerateAdjustmentTrialBalanceBigQuery indicates an expected call of GenerateAdjustmentTrialBalanceBigQuery.
func (mr *MockAccountingServiceMockRecorder) GenerateAdjustmentTrialBalanceBigQuery(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAdjustmentTrialBalanceBigQuery", reflect.TypeOf((*MockAccountingService)(nil).GenerateAdjustmentTrialBalanceBigQuery), ctx, in)
}

// GenerateTrialBalanceBigQuery mocks base method.
func (m *MockAccountingService) GenerateTrialBalanceBigQuery(ctx context.Context, date time.Time, isAdjustment bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTrialBalanceBigQuery", ctx, date, isAdjustment)
	ret0, _ := ret[0].(error)
	return ret0
}

// GenerateTrialBalanceBigQuery indicates an expected call of GenerateTrialBalanceBigQuery.
func (mr *MockAccountingServiceMockRecorder) GenerateTrialBalanceBigQuery(ctx, date, isAdjustment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTrialBalanceBigQuery", reflect.TypeOf((*MockAccountingService)(nil).GenerateTrialBalanceBigQuery), ctx, date, isAdjustment)
}

// GetBalanceSheet mocks base method.
func (m *MockAccountingService) GetBalanceSheet(ctx context.Context, opts models.BalanceSheetFilterOptions) (models.GetBalanceSheetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalanceSheet", ctx, opts)
	ret0, _ := ret[0].(models.GetBalanceSheetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalanceSheet indicates an expected call of GetBalanceSheet.
func (mr *MockAccountingServiceMockRecorder) GetBalanceSheet(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalanceSheet", reflect.TypeOf((*MockAccountingService)(nil).GetBalanceSheet), ctx, opts)
}

// GetGeneralLedger mocks base method.
func (m *MockAccountingService) GetGeneralLedger(ctx context.Context, opts models.SubLedgerFilterOptions) (models.SubLedgerAccountResponse, []models.GetSubLedgerOut, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGeneralLedger", ctx, opts)
	ret0, _ := ret[0].(models.SubLedgerAccountResponse)
	ret1, _ := ret[1].([]models.GetSubLedgerOut)
	ret2, _ := ret[2].(int)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetGeneralLedger indicates an expected call of GetGeneralLedger.
func (mr *MockAccountingServiceMockRecorder) GetGeneralLedger(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGeneralLedger", reflect.TypeOf((*MockAccountingService)(nil).GetGeneralLedger), ctx, opts)
}

// GetSubLedger mocks base method.
func (m *MockAccountingService) GetSubLedger(ctx context.Context, opts models.SubLedgerFilterOptions) (models.SubLedgerAccountResponse, []models.GetSubLedgerOut, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubLedger", ctx, opts)
	ret0, _ := ret[0].(models.SubLedgerAccountResponse)
	ret1, _ := ret[1].([]models.GetSubLedgerOut)
	ret2, _ := ret[2].(int)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetSubLedger indicates an expected call of GetSubLedger.
func (mr *MockAccountingServiceMockRecorder) GetSubLedger(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubLedger", reflect.TypeOf((*MockAccountingService)(nil).GetSubLedger), ctx, opts)
}

// GetSubLedgerAccounts mocks base method.
func (m *MockAccountingService) GetSubLedgerAccounts(ctx context.Context, opts models.SubLedgerAccountsFilterOptions) ([]models.GetSubLedgerAccountsOut, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubLedgerAccounts", ctx, opts)
	ret0, _ := ret[0].([]models.GetSubLedgerAccountsOut)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSubLedgerAccounts indicates an expected call of GetSubLedgerAccounts.
func (mr *MockAccountingServiceMockRecorder) GetSubLedgerAccounts(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubLedgerAccounts", reflect.TypeOf((*MockAccountingService)(nil).GetSubLedgerAccounts), ctx, opts)
}

// GetSubLedgerCount mocks base method.
func (m *MockAccountingService) GetSubLedgerCount(ctx context.Context, opts models.SubLedgerFilterOptions) (models.GetSubLedgerCountOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubLedgerCount", ctx, opts)
	ret0, _ := ret[0].(models.GetSubLedgerCountOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubLedgerCount indicates an expected call of GetSubLedgerCount.
func (mr *MockAccountingServiceMockRecorder) GetSubLedgerCount(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubLedgerCount", reflect.TypeOf((*MockAccountingService)(nil).GetSubLedgerCount), ctx, opts)
}

// GetTrialBalance mocks base method.
func (m *MockAccountingService) GetTrialBalance(ctx context.Context, opts models.TrialBalanceFilterOptions) (models.GetTrialBalanceResponses, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrialBalance", ctx, opts)
	ret0, _ := ret[0].(models.GetTrialBalanceResponses)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrialBalance indicates an expected call of GetTrialBalance.
func (mr *MockAccountingServiceMockRecorder) GetTrialBalance(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrialBalance", reflect.TypeOf((*MockAccountingService)(nil).GetTrialBalance), ctx, opts)
}

// GetTrialBalanceBySubCategoryCode mocks base method.
func (m *MockAccountingService) GetTrialBalanceBySubCategoryCode(ctx context.Context, opts models.TrialBalanceFilterOptions) (models.TrialBalanceBySubCategoryOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrialBalanceBySubCategoryCode", ctx, opts)
	ret0, _ := ret[0].(models.TrialBalanceBySubCategoryOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrialBalanceBySubCategoryCode indicates an expected call of GetTrialBalanceBySubCategoryCode.
func (mr *MockAccountingServiceMockRecorder) GetTrialBalanceBySubCategoryCode(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrialBalanceBySubCategoryCode", reflect.TypeOf((*MockAccountingService)(nil).GetTrialBalanceBySubCategoryCode), ctx, opts)
}

// GetTrialBalanceDetails mocks base method.
func (m *MockAccountingService) GetTrialBalanceDetails(ctx context.Context, opts models.TrialBalanceDetailsFilterOptions) ([]models.TrialBalanceDetailOut, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrialBalanceDetails", ctx, opts)
	ret0, _ := ret[0].([]models.TrialBalanceDetailOut)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTrialBalanceDetails indicates an expected call of GetTrialBalanceDetails.
func (mr *MockAccountingServiceMockRecorder) GetTrialBalanceDetails(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrialBalanceDetails", reflect.TypeOf((*MockAccountingService)(nil).GetTrialBalanceDetails), ctx, opts)
}

// GetTrialBalanceFromGCS mocks base method.
func (m *MockAccountingService) GetTrialBalanceFromGCS(ctx context.Context, opts models.TrialBalanceDetailsFilterOptions) ([]models.TrialBalanceDetailOut, models.TrialBalanceBySubCategoryOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrialBalanceFromGCS", ctx, opts)
	ret0, _ := ret[0].([]models.TrialBalanceDetailOut)
	ret1, _ := ret[1].(models.TrialBalanceBySubCategoryOut)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTrialBalanceFromGCS indicates an expected call of GetTrialBalanceFromGCS.
func (mr *MockAccountingServiceMockRecorder) GetTrialBalanceFromGCS(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrialBalanceFromGCS", reflect.TypeOf((*MockAccountingService)(nil).GetTrialBalanceFromGCS), ctx, opts)
}

// SendEmailTrialBalanceDetails mocks base method.
func (m *MockAccountingService) SendEmailTrialBalanceDetails(ctx context.Context, opts models.TrialBalanceDetailsFilterOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEmailTrialBalanceDetails", ctx, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendEmailTrialBalanceDetails indicates an expected call of SendEmailTrialBalanceDetails.
func (mr *MockAccountingServiceMockRecorder) SendEmailTrialBalanceDetails(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmailTrialBalanceDetails", reflect.TypeOf((*MockAccountingService)(nil).SendEmailTrialBalanceDetails), ctx, opts)
}

// SendEmailTrialBalanceSummary mocks base method.
func (m *MockAccountingService) SendEmailTrialBalanceSummary(ctx context.Context, opts models.TrialBalanceFilterOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEmailTrialBalanceSummary", ctx, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendEmailTrialBalanceSummary indicates an expected call of SendEmailTrialBalanceSummary.
func (mr *MockAccountingServiceMockRecorder) SendEmailTrialBalanceSummary(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmailTrialBalanceSummary", reflect.TypeOf((*MockAccountingService)(nil).SendEmailTrialBalanceSummary), ctx, opts)
}

// SendSubLedgerCSVToEmail mocks base method.
func (m *MockAccountingService) SendSubLedgerCSVToEmail(ctx context.Context, opts models.SubLedgerFilterOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendSubLedgerCSVToEmail", ctx, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendSubLedgerCSVToEmail indicates an expected call of SendSubLedgerCSVToEmail.
func (mr *MockAccountingServiceMockRecorder) SendSubLedgerCSVToEmail(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendSubLedgerCSVToEmail", reflect.TypeOf((*MockAccountingService)(nil).SendSubLedgerCSVToEmail), ctx, opts)
}

// SendToEmailGetTrialBalanceDetails mocks base method.
func (m *MockAccountingService) SendToEmailGetTrialBalanceDetails(ctx context.Context, opts models.TrialBalanceDetailsFilterOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendToEmailGetTrialBalanceDetails", ctx, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendToEmailGetTrialBalanceDetails indicates an expected call of SendToEmailGetTrialBalanceDetails.
func (mr *MockAccountingServiceMockRecorder) SendToEmailGetTrialBalanceDetails(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendToEmailGetTrialBalanceDetails", reflect.TypeOf((*MockAccountingService)(nil).SendToEmailGetTrialBalanceDetails), ctx, opts)
}
