// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/services/account_service.go
//
// Generated by this command:
//
//	mockgen -source=./internal/services/account_service.go -destination=./internal/services/mock/account_service_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	bytes "bytes"
	context "context"
	multipart "mime/multipart"
	reflect "reflect"

	models "bitbucket.org/Amartha/go-accounting/internal/models"
	gocustomer "bitbucket.org/Amartha/go-accounting/internal/pkg/gocustomer"
	gomock "go.uber.org/mock/gomock"
)

// MockAccountService is a mock of AccountService interface.
type MockAccountService struct {
	ctrl     *gomock.Controller
	recorder *MockAccountServiceMockRecorder
	isgomock struct{}
}

// MockAccountServiceMockRecorder is the mock recorder for MockAccountService.
type MockAccountServiceMockRecorder struct {
	mock *MockAccountService
}

// NewMockAccountService creates a new mock instance.
func NewMockAccountService(ctrl *gomock.Controller) *MockAccountService {
	mock := &MockAccountService{ctrl: ctrl}
	mock.recorder = &MockAccountServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountService) EXPECT() *MockAccountServiceMockRecorder {
	return m.recorder
}

// CheckAltIdIsExist mocks base method.
func (m *MockAccountService) CheckAltIdIsExist(ctx context.Context, altId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAltIdIsExist", ctx, altId)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckAltIdIsExist indicates an expected call of CheckAltIdIsExist.
func (mr *MockAccountServiceMockRecorder) CheckAltIdIsExist(ctx, altId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAltIdIsExist", reflect.TypeOf((*MockAccountService)(nil).CheckAltIdIsExist), ctx, altId)
}

// ConsumerCreateAccountMigration mocks base method.
func (m *MockAccountService) ConsumerCreateAccountMigration(ctx context.Context, in models.CreateAccount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsumerCreateAccountMigration", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConsumerCreateAccountMigration indicates an expected call of ConsumerCreateAccountMigration.
func (mr *MockAccountServiceMockRecorder) ConsumerCreateAccountMigration(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumerCreateAccountMigration", reflect.TypeOf((*MockAccountService)(nil).ConsumerCreateAccountMigration), ctx, in)
}

// Create mocks base method.
func (m *MockAccountService) Create(ctx context.Context, in models.CreateAccount) (models.CreateAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, in)
	ret0, _ := ret[0].(models.CreateAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAccountServiceMockRecorder) Create(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAccountService)(nil).Create), ctx, in)
}

// CreateBranchPointAccount mocks base method.
func (m *MockAccountService) CreateBranchPointAccount(ctx context.Context, in models.CreateAccount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBranchPointAccount", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBranchPointAccount indicates an expected call of CreateBranchPointAccount.
func (mr *MockAccountServiceMockRecorder) CreateBranchPointAccount(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBranchPointAccount", reflect.TypeOf((*MockAccountService)(nil).CreateBranchPointAccount), ctx, in)
}

// CreateCategoryCodeSeq mocks base method.
func (m *MockAccountService) CreateCategoryCodeSeq(ctx context.Context, in models.DoCreateCategoryCodeSeqRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCategoryCodeSeq", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCategoryCodeSeq indicates an expected call of CreateCategoryCodeSeq.
func (mr *MockAccountServiceMockRecorder) CreateCategoryCodeSeq(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCategoryCodeSeq", reflect.TypeOf((*MockAccountService)(nil).CreateCategoryCodeSeq), ctx, in)
}

// CreateLenderInstitutionAccount mocks base method.
func (m *MockAccountService) CreateLenderInstitutionAccount(ctx context.Context, in models.CreateAccount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLenderInstitutionAccount", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateLenderInstitutionAccount indicates an expected call of CreateLenderInstitutionAccount.
func (mr *MockAccountServiceMockRecorder) CreateLenderInstitutionAccount(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLenderInstitutionAccount", reflect.TypeOf((*MockAccountService)(nil).CreateLenderInstitutionAccount), ctx, in)
}

// CreateLoanAccount mocks base method.
func (m *MockAccountService) CreateLoanAccount(ctx context.Context, in models.CreateAccount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLoanAccount", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateLoanAccount indicates an expected call of CreateLoanAccount.
func (mr *MockAccountServiceMockRecorder) CreateLoanAccount(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLoanAccount", reflect.TypeOf((*MockAccountService)(nil).CreateLoanAccount), ctx, in)
}

// CreateLoanPartnerAccount mocks base method.
func (m *MockAccountService) CreateLoanPartnerAccount(ctx context.Context, in models.CreateAccountLoanPartner) (models.AccountsLoanPartner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLoanPartnerAccount", ctx, in)
	ret0, _ := ret[0].(models.AccountsLoanPartner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLoanPartnerAccount indicates an expected call of CreateLoanPartnerAccount.
func (mr *MockAccountServiceMockRecorder) CreateLoanPartnerAccount(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLoanPartnerAccount", reflect.TypeOf((*MockAccountService)(nil).CreateLoanPartnerAccount), ctx, in)
}

// DownloadCSVGetAccountList mocks base method.
func (m *MockAccountService) DownloadCSVGetAccountList(ctx context.Context, in []models.GetAccountOut) (*bytes.Buffer, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadCSVGetAccountList", ctx, in)
	ret0, _ := ret[0].(*bytes.Buffer)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DownloadCSVGetAccountList indicates an expected call of DownloadCSVGetAccountList.
func (mr *MockAccountServiceMockRecorder) DownloadCSVGetAccountList(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadCSVGetAccountList", reflect.TypeOf((*MockAccountService)(nil).DownloadCSVGetAccountList), ctx, in)
}

// GetAccountList mocks base method.
func (m *MockAccountService) GetAccountList(ctx context.Context, opts models.AccountFilterOptions) ([]models.GetAccountOut, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountList", ctx, opts)
	ret0, _ := ret[0].([]models.GetAccountOut)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAccountList indicates an expected call of GetAccountList.
func (mr *MockAccountServiceMockRecorder) GetAccountList(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountList", reflect.TypeOf((*MockAccountService)(nil).GetAccountList), ctx, opts)
}

// GetAllAccountNumbersByParam mocks base method.
func (m *MockAccountService) GetAllAccountNumbersByParam(ctx context.Context, in models.GetAllAccountNumbersByParamIn) ([]models.GetAllAccountNumbersByParamOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllAccountNumbersByParam", ctx, in)
	ret0, _ := ret[0].([]models.GetAllAccountNumbersByParamOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllAccountNumbersByParam indicates an expected call of GetAllAccountNumbersByParam.
func (mr *MockAccountServiceMockRecorder) GetAllAccountNumbersByParam(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllAccountNumbersByParam", reflect.TypeOf((*MockAccountService)(nil).GetAllAccountNumbersByParam), ctx, in)
}

// GetAllCategoryCodeSeq mocks base method.
func (m *MockAccountService) GetAllCategoryCodeSeq(ctx context.Context) ([]models.DoGetAllCategoryCodeSeqResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCategoryCodeSeq", ctx)
	ret0, _ := ret[0].([]models.DoGetAllCategoryCodeSeqResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCategoryCodeSeq indicates an expected call of GetAllCategoryCodeSeq.
func (mr *MockAccountServiceMockRecorder) GetAllCategoryCodeSeq(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCategoryCodeSeq", reflect.TypeOf((*MockAccountService)(nil).GetAllCategoryCodeSeq), ctx)
}

// GetLenderAccountByCIHAccountNumber mocks base method.
func (m *MockAccountService) GetLenderAccountByCIHAccountNumber(ctx context.Context, accountNumber string) (models.AccountLender, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLenderAccountByCIHAccountNumber", ctx, accountNumber)
	ret0, _ := ret[0].(models.AccountLender)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLenderAccountByCIHAccountNumber indicates an expected call of GetLenderAccountByCIHAccountNumber.
func (mr *MockAccountServiceMockRecorder) GetLenderAccountByCIHAccountNumber(ctx, accountNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLenderAccountByCIHAccountNumber", reflect.TypeOf((*MockAccountService)(nil).GetLenderAccountByCIHAccountNumber), ctx, accountNumber)
}

// GetLoanAdvanceAccountByLoanAccount mocks base method.
func (m *MockAccountService) GetLoanAdvanceAccountByLoanAccount(ctx context.Context, loanAccountNumber string) (models.AccountLoan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoanAdvanceAccountByLoanAccount", ctx, loanAccountNumber)
	ret0, _ := ret[0].(models.AccountLoan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLoanAdvanceAccountByLoanAccount indicates an expected call of GetLoanAdvanceAccountByLoanAccount.
func (mr *MockAccountServiceMockRecorder) GetLoanAdvanceAccountByLoanAccount(ctx, loanAccountNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoanAdvanceAccountByLoanAccount", reflect.TypeOf((*MockAccountService)(nil).GetLoanAdvanceAccountByLoanAccount), ctx, loanAccountNumber)
}

// GetOneByAccountNumber mocks base method.
func (m *MockAccountService) GetOneByAccountNumber(ctx context.Context, accountNumber string) (models.GetAccountOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOneByAccountNumber", ctx, accountNumber)
	ret0, _ := ret[0].(models.GetAccountOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOneByAccountNumber indicates an expected call of GetOneByAccountNumber.
func (mr *MockAccountServiceMockRecorder) GetOneByAccountNumber(ctx, accountNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOneByAccountNumber", reflect.TypeOf((*MockAccountService)(nil).GetOneByAccountNumber), ctx, accountNumber)
}

// GetOneByLegacyID mocks base method.
func (m *MockAccountService) GetOneByLegacyID(ctx context.Context, legacyID string) (models.GetAccountOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOneByLegacyID", ctx, legacyID)
	ret0, _ := ret[0].(models.GetAccountOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOneByLegacyID indicates an expected call of GetOneByLegacyID.
func (mr *MockAccountServiceMockRecorder) GetOneByLegacyID(ctx, legacyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOneByLegacyID", reflect.TypeOf((*MockAccountService)(nil).GetOneByLegacyID), ctx, legacyID)
}

// ProcessUploadAccounts mocks base method.
func (m *MockAccountService) ProcessUploadAccounts(ctx context.Context, file *multipart.FileHeader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessUploadAccounts", ctx, file)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessUploadAccounts indicates an expected call of ProcessUploadAccounts.
func (mr *MockAccountServiceMockRecorder) ProcessUploadAccounts(ctx, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessUploadAccounts", reflect.TypeOf((*MockAccountService)(nil).ProcessUploadAccounts), ctx, file)
}

// Update mocks base method.
func (m *MockAccountService) Update(ctx context.Context, in models.UpdateAccount) (models.UpdateAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, in)
	ret0, _ := ret[0].(models.UpdateAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockAccountServiceMockRecorder) Update(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAccountService)(nil).Update), ctx, in)
}

// UpdateAccountByCustomerData mocks base method.
func (m *MockAccountService) UpdateAccountByCustomerData(ctx context.Context, in gocustomer.CustomerEventPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccountByCustomerData", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAccountByCustomerData indicates an expected call of UpdateAccountByCustomerData.
func (mr *MockAccountServiceMockRecorder) UpdateAccountByCustomerData(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccountByCustomerData", reflect.TypeOf((*MockAccountService)(nil).UpdateAccountByCustomerData), ctx, in)
}

// UpdateAccountEntity mocks base method.
func (m *MockAccountService) UpdateAccountEntity(ctx context.Context, in models.UpdateAccountEntity) (models.UpdateAccountEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccountEntity", ctx, in)
	ret0, _ := ret[0].(models.UpdateAccountEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAccountEntity indicates an expected call of UpdateAccountEntity.
func (mr *MockAccountServiceMockRecorder) UpdateAccountEntity(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccountEntity", reflect.TypeOf((*MockAccountService)(nil).UpdateAccountEntity), ctx, in)
}

// UpdateCategoryCodeSeq mocks base method.
func (m *MockAccountService) UpdateCategoryCodeSeq(ctx context.Context, in models.DoUpdateCategoryCodeSeqRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCategoryCodeSeq", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCategoryCodeSeq indicates an expected call of UpdateCategoryCodeSeq.
func (mr *MockAccountServiceMockRecorder) UpdateCategoryCodeSeq(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCategoryCodeSeq", reflect.TypeOf((*MockAccountService)(nil).UpdateCategoryCodeSeq), ctx, in)
}
