// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/services/coa_type_service.go
//
// Generated by this command:
//
//	mockgen -source=./internal/services/coa_type_service.go -destination=./internal/services/mock/coa_type_service_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "bitbucket.org/Amartha/go-accounting/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockCOATypeService is a mock of COATypeService interface.
type MockCOATypeService struct {
	ctrl     *gomock.Controller
	recorder *MockCOATypeServiceMockRecorder
	isgomock struct{}
}

// MockCOATypeServiceMockRecorder is the mock recorder for MockCOATypeService.
type MockCOATypeServiceMockRecorder struct {
	mock *MockCOATypeService
}

// NewMockCOATypeService creates a new mock instance.
func NewMockCOATypeService(ctrl *gomock.Controller) *MockCOATypeService {
	mock := &MockCOATypeService{ctrl: ctrl}
	mock.recorder = &MockCOATypeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCOATypeService) EXPECT() *MockCOATypeServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCOATypeService) Create(ctx context.Context, in models.CreateCOATypeIn) (*models.COAType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, in)
	ret0, _ := ret[0].(*models.COAType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCOATypeServiceMockRecorder) Create(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCOATypeService)(nil).Create), ctx, in)
}

// GetAll mocks base method.
func (m *MockCOATypeService) GetAll(ctx context.Context) ([]models.COATypeCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]models.COATypeCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockCOATypeServiceMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockCOATypeService)(nil).GetAll), ctx)
}

// Update mocks base method.
func (m *MockCOATypeService) Update(ctx context.Context, in models.UpdateCOAType) (models.UpdateCOAType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, in)
	ret0, _ := ret[0].(models.UpdateCOAType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCOATypeServiceMockRecorder) Update(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCOATypeService)(nil).Update), ctx, in)
}
