// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/services/dlq_processor_service.go
//
// Generated by this command:
//
//	mockgen -source=./internal/services/dlq_processor_service.go -destination=./internal/services/mock/dlq_processor_service_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "bitbucket.org/Amartha/go-accounting/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockDLQProcessorService is a mock of DLQProcessorService interface.
type MockDLQProcessorService struct {
	ctrl     *gomock.Controller
	recorder *MockDLQProcessorServiceMockRecorder
	isgomock struct{}
}

// MockDLQProcessorServiceMockRecorder is the mock recorder for MockDLQProcessorService.
type MockDLQProcessorServiceMockRecorder struct {
	mock *MockDLQProcessorService
}

// NewMockDLQProcessorService creates a new mock instance.
func NewMockDLQProcessorService(ctrl *gomock.Controller) *MockDLQProcessorService {
	mock := &MockDLQProcessorService{ctrl: ctrl}
	mock.recorder = &MockDLQProcessorServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDLQProcessorService) EXPECT() *MockDLQProcessorServiceMockRecorder {
	return m.recorder
}

// SendNotificationAccountT24Failure mocks base method.
func (m *MockDLQProcessorService) SendNotificationAccountT24Failure(ctx context.Context, message models.AccountError) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendNotificationAccountT24Failure", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendNotificationAccountT24Failure indicates an expected call of SendNotificationAccountT24Failure.
func (mr *MockDLQProcessorServiceMockRecorder) SendNotificationAccountT24Failure(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendNotificationAccountT24Failure", reflect.TypeOf((*MockDLQProcessorService)(nil).SendNotificationAccountT24Failure), ctx, message)
}

// SendNotificationJournalFailure mocks base method.
func (m *MockDLQProcessorService) SendNotificationJournalFailure(ctx context.Context, message models.JournalError) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendNotificationJournalFailure", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendNotificationJournalFailure indicates an expected call of SendNotificationJournalFailure.
func (mr *MockDLQProcessorServiceMockRecorder) SendNotificationJournalFailure(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendNotificationJournalFailure", reflect.TypeOf((*MockDLQProcessorService)(nil).SendNotificationJournalFailure), ctx, message)
}
