// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/services/journal_service.go
//
// Generated by this command:
//
//	mockgen -source=./internal/services/journal_service.go -destination=./internal/services/mock/journal_service_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	multipart "mime/multipart"
	reflect "reflect"

	models "bitbucket.org/Amartha/go-accounting/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockJournalService is a mock of JournalService interface.
type MockJournalService struct {
	ctrl     *gomock.Controller
	recorder *MockJournalServiceMockRecorder
	isgomock struct{}
}

// MockJournalServiceMockRecorder is the mock recorder for MockJournalService.
type MockJournalServiceMockRecorder struct {
	mock *MockJournalService
}

// NewMockJournalService creates a new mock instance.
func NewMockJournalService(ctrl *gomock.Controller) *MockJournalService {
	mock := &MockJournalService{ctrl: ctrl}
	mock.recorder = &MockJournalServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJournalService) EXPECT() *MockJournalServiceMockRecorder {
	return m.recorder
}

// ConsumerInsertTransaction mocks base method.
func (m *MockJournalService) ConsumerInsertTransaction(ctx context.Context, req models.JournalRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsumerInsertTransaction", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConsumerInsertTransaction indicates an expected call of ConsumerInsertTransaction.
func (mr *MockJournalServiceMockRecorder) ConsumerInsertTransaction(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumerInsertTransaction", reflect.TypeOf((*MockJournalService)(nil).ConsumerInsertTransaction), ctx, req)
}

// GetJournalByTransactionId mocks base method.
func (m *MockJournalService) GetJournalByTransactionId(ctx context.Context, transactionId string) ([]models.GetJournalDetailOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJournalByTransactionId", ctx, transactionId)
	ret0, _ := ret[0].([]models.GetJournalDetailOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJournalByTransactionId indicates an expected call of GetJournalByTransactionId.
func (mr *MockJournalServiceMockRecorder) GetJournalByTransactionId(ctx, transactionId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJournalByTransactionId", reflect.TypeOf((*MockJournalService)(nil).GetJournalByTransactionId), ctx, transactionId)
}

// InsertJournalTransaction mocks base method.
func (m *MockJournalService) InsertJournalTransaction(ctx context.Context, request models.JournalRequest) ([]models.JournalEntryCreatedRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertJournalTransaction", ctx, request)
	ret0, _ := ret[0].([]models.JournalEntryCreatedRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertJournalTransaction indicates an expected call of InsertJournalTransaction.
func (mr *MockJournalServiceMockRecorder) InsertJournalTransaction(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertJournalTransaction", reflect.TypeOf((*MockJournalService)(nil).InsertJournalTransaction), ctx, request)
}

// ProcessUploadJournal mocks base method.
func (m *MockJournalService) ProcessUploadJournal(ctx context.Context, file *multipart.FileHeader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessUploadJournal", ctx, file)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessUploadJournal indicates an expected call of ProcessUploadJournal.
func (mr *MockJournalServiceMockRecorder) ProcessUploadJournal(ctx, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessUploadJournal", reflect.TypeOf((*MockJournalService)(nil).ProcessUploadJournal), ctx, file)
}

// PublishJournalTransaction mocks base method.
func (m *MockJournalService) PublishJournalTransaction(ctx context.Context, req models.JournalRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishJournalTransaction", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishJournalTransaction indicates an expected call of PublishJournalTransaction.
func (mr *MockJournalServiceMockRecorder) PublishJournalTransaction(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishJournalTransaction", reflect.TypeOf((*MockJournalService)(nil).PublishJournalTransaction), ctx, req)
}

// RetryPublishToJournalEntryCreated mocks base method.
func (m *MockJournalService) RetryPublishToJournalEntryCreated(ctx context.Context, data models.JournalEntryCreatedRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetryPublishToJournalEntryCreated", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// RetryPublishToJournalEntryCreated indicates an expected call of RetryPublishToJournalEntryCreated.
func (mr *MockJournalServiceMockRecorder) RetryPublishToJournalEntryCreated(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetryPublishToJournalEntryCreated", reflect.TypeOf((*MockJournalService)(nil).RetryPublishToJournalEntryCreated), ctx, data)
}
