// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/services/loan_partner_account_service.go
//
// Generated by this command:
//
//	mockgen -source=./internal/services/loan_partner_account_service.go -destination=./internal/services/mock/loan_partner_account_service_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "bitbucket.org/Amartha/go-accounting/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockLoanPartnerService is a mock of LoanPartnerService interface.
type MockLoanPartnerService struct {
	ctrl     *gomock.Controller
	recorder *MockLoanPartnerServiceMockRecorder
	isgomock struct{}
}

// MockLoanPartnerServiceMockRecorder is the mock recorder for MockLoanPartnerService.
type MockLoanPartnerServiceMockRecorder struct {
	mock *MockLoanPartnerService
}

// NewMockLoanPartnerService creates a new mock instance.
func NewMockLoanPartnerService(ctrl *gomock.Controller) *MockLoanPartnerService {
	mock := &MockLoanPartnerService{ctrl: ctrl}
	mock.recorder = &MockLoanPartnerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoanPartnerService) EXPECT() *MockLoanPartnerServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockLoanPartnerService) Create(ctx context.Context, in models.LoanPartnerAccount) (models.LoanPartnerAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, in)
	ret0, _ := ret[0].(models.LoanPartnerAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockLoanPartnerServiceMockRecorder) Create(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLoanPartnerService)(nil).Create), ctx, in)
}

// GetByParams mocks base method.
func (m *MockLoanPartnerService) GetByParams(ctx context.Context, in models.GetLoanPartnerAccountByParamsIn) ([]models.LoanPartnerAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByParams", ctx, in)
	ret0, _ := ret[0].([]models.LoanPartnerAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByParams indicates an expected call of GetByParams.
func (mr *MockLoanPartnerServiceMockRecorder) GetByParams(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByParams", reflect.TypeOf((*MockLoanPartnerService)(nil).GetByParams), ctx, in)
}

// Update mocks base method.
func (m *MockLoanPartnerService) Update(ctx context.Context, in models.UpdateLoanPartnerAccount) (models.UpdateLoanPartnerAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, in)
	ret0, _ := ret[0].(models.UpdateLoanPartnerAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockLoanPartnerServiceMockRecorder) Update(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockLoanPartnerService)(nil).Update), ctx, in)
}
