// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/services/migration_service.go
//
// Generated by this command:
//
//	mockgen -source=./internal/services/migration_service.go -destination=./internal/services/mock/migration_service_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "bitbucket.org/Amartha/go-accounting/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockMigrationService is a mock of MigrationService interface.
type MockMigrationService struct {
	ctrl     *gomock.Controller
	recorder *MockMigrationServiceMockRecorder
	isgomock struct{}
}

// MockMigrationServiceMockRecorder is the mock recorder for MockMigrationService.
type MockMigrationServiceMockRecorder struct {
	mock *MockMigrationService
}

// NewMockMigrationService creates a new mock instance.
func NewMockMigrationService(ctrl *gomock.Controller) *MockMigrationService {
	mock := &MockMigrationService{ctrl: ctrl}
	mock.recorder = &MockMigrationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMigrationService) EXPECT() *MockMigrationServiceMockRecorder {
	return m.recorder
}

// BucketsJournalLoad mocks base method.
func (m *MockMigrationService) BucketsJournalLoad(ctx context.Context, req models.MigrationBucketsJournalLoadRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BucketsJournalLoad", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// BucketsJournalLoad indicates an expected call of BucketsJournalLoad.
func (mr *MockMigrationServiceMockRecorder) BucketsJournalLoad(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BucketsJournalLoad", reflect.TypeOf((*MockMigrationService)(nil).BucketsJournalLoad), ctx, req)
}
