// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/services/product_type_service.go
//
// Generated by this command:
//
//	mockgen -source=./internal/services/product_type_service.go -destination=./internal/services/mock/product_type_service_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "bitbucket.org/Amartha/go-accounting/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockProductTypeService is a mock of ProductTypeService interface.
type MockProductTypeService struct {
	ctrl     *gomock.Controller
	recorder *MockProductTypeServiceMockRecorder
	isgomock struct{}
}

// MockProductTypeServiceMockRecorder is the mock recorder for MockProductTypeService.
type MockProductTypeServiceMockRecorder struct {
	mock *MockProductTypeService
}

// NewMockProductTypeService creates a new mock instance.
func NewMockProductTypeService(ctrl *gomock.Controller) *MockProductTypeService {
	mock := &MockProductTypeService{ctrl: ctrl}
	mock.recorder = &MockProductTypeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductTypeService) EXPECT() *MockProductTypeServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockProductTypeService) Create(ctx context.Context, req models.CreateProductTypeRequest) (*models.ProductType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*models.ProductType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockProductTypeServiceMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProductTypeService)(nil).Create), ctx, req)
}

// GetAll mocks base method.
func (m *MockProductTypeService) GetAll(ctx context.Context) ([]models.ProductType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]models.ProductType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockProductTypeServiceMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockProductTypeService)(nil).GetAll), ctx)
}

// Update mocks base method.
func (m *MockProductTypeService) Update(ctx context.Context, in models.UpdateProductType) (models.UpdateProductType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, in)
	ret0, _ := ret[0].(models.UpdateProductType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockProductTypeServiceMockRecorder) Update(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProductTypeService)(nil).Update), ctx, in)
}
