// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/services/publisher.go
//
// Generated by this command:
//
//	mockgen -source=./internal/services/publisher.go -destination=./internal/services/mock/publisher_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "bitbucket.org/Amartha/go-accounting/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockPublisherService is a mock of PublisherService interface.
type MockPublisherService struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherServiceMockRecorder
	isgomock struct{}
}

// MockPublisherServiceMockRecorder is the mock recorder for MockPublisherService.
type MockPublisherServiceMockRecorder struct {
	mock *MockPublisherService
}

// NewMockPublisherService creates a new mock instance.
func NewMockPublisherService(ctrl *gomock.Controller) *MockPublisherService {
	mock := &MockPublisherService{ctrl: ctrl}
	mock.recorder = &MockPublisherServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisherService) EXPECT() *MockPublisherServiceMockRecorder {
	return m.recorder
}

// PublishMessage mocks base method.
func (m *MockPublisherService) PublishMessage(ctx context.Context, in models.PublishRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishMessage", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishMessage indicates an expected call of PublishMessage.
func (mr *MockPublisherServiceMockRecorder) PublishMessage(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishMessage", reflect.TypeOf((*MockPublisherService)(nil).PublishMessage), ctx, in)
}
