// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/services/retry_service.go
//
// Generated by this command:
//
//	mockgen -source=./internal/services/retry_service.go -destination=./internal/services/mock/retry_service_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "bitbucket.org/Amartha/go-accounting/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockRetryService is a mock of RetryService interface.
type MockRetryService struct {
	ctrl     *gomock.Controller
	recorder *MockRetryServiceMockRecorder
	isgomock struct{}
}

// MockRetryServiceMockRecorder is the mock recorder for MockRetryService.
type MockRetryServiceMockRecorder struct {
	mock *MockRetryService
}

// NewMockRetryService creates a new mock instance.
func NewMockRetryService(ctrl *gomock.Controller) *MockRetryService {
	mock := &MockRetryService{ctrl: ctrl}
	mock.recorder = &MockRetryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRetryService) EXPECT() *MockRetryServiceMockRecorder {
	return m.recorder
}

// RetryInsertJournalTransaction mocks base method.
func (m *MockRetryService) RetryInsertJournalTransaction(ctx context.Context, req models.JournalError) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetryInsertJournalTransaction", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// RetryInsertJournalTransaction indicates an expected call of RetryInsertJournalTransaction.
func (mr *MockRetryServiceMockRecorder) RetryInsertJournalTransaction(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetryInsertJournalTransaction", reflect.TypeOf((*MockRetryService)(nil).RetryInsertJournalTransaction), ctx, req)
}

// RetryUpdateLegacyId mocks base method.
func (m *MockRetryService) RetryUpdateLegacyId(ctx context.Context, req models.AccountError) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetryUpdateLegacyId", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// RetryUpdateLegacyId indicates an expected call of RetryUpdateLegacyId.
func (mr *MockRetryServiceMockRecorder) RetryUpdateLegacyId(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetryUpdateLegacyId", reflect.TypeOf((*MockRetryService)(nil).RetryUpdateLegacyId), ctx, req)
}
