// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/services/trial_balance_service.go
//
// Generated by this command:
//
//	mockgen -source=./internal/services/trial_balance_service.go -destination=./internal/services/mock/trial_balance_service_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "bitbucket.org/Amartha/go-accounting/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockTrialBalanceService is a mock of TrialBalanceService interface.
type MockTrialBalanceService struct {
	ctrl     *gomock.Controller
	recorder *MockTrialBalanceServiceMockRecorder
	isgomock struct{}
}

// MockTrialBalanceServiceMockRecorder is the mock recorder for MockTrialBalanceService.
type MockTrialBalanceServiceMockRecorder struct {
	mock *MockTrialBalanceService
}

// NewMockTrialBalanceService creates a new mock instance.
func NewMockTrialBalanceService(ctrl *gomock.Controller) *MockTrialBalanceService {
	mock := &MockTrialBalanceService{ctrl: ctrl}
	mock.recorder = &MockTrialBalanceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrialBalanceService) EXPECT() *MockTrialBalanceServiceMockRecorder {
	return m.recorder
}

// CloseTrialBalance mocks base method.
func (m *MockTrialBalanceService) CloseTrialBalance(ctx context.Context, in models.CloseTrialBalanceRequest) (models.TrialBalancePeriod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseTrialBalance", ctx, in)
	ret0, _ := ret[0].(models.TrialBalancePeriod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CloseTrialBalance indicates an expected call of CloseTrialBalance.
func (mr *MockTrialBalanceServiceMockRecorder) CloseTrialBalance(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseTrialBalance", reflect.TypeOf((*MockTrialBalanceService)(nil).CloseTrialBalance), ctx, in)
}
