// Code generated by errorGen. DO NOT EDIT.

package models

import "errors"

const (
	ErrKeyCreateSubCategoryRequestCodeMax            = "CreateSubCategoryRequest.code_max"
	ErrKeyCreateSubCategoryRequestCodeMin            = "CreateSubCategoryRequest.code_min"
	ErrKeyCreateSubCategoryRequestCodeNumeric        = "CreateSubCategoryRequest.code_numeric"
	ErrKeyCreateSubCategoryRequestCodeRequired       = "CreateSubCategoryRequest.code_required"
	ErrKeyCreateSubCategoryRequestNameMax            = "CreateSubCategoryRequest.name_max"
	ErrKeyUpdateSubCategoryRequestNameMax            = "UpdateSubCategoryRequest.name_max"
	ErrKeyDoCreateAccountRequestNameMax              = "DoCreateAccountRequest.name_max"
	ErrKeyDoCreateCategoryRequestNameMax             = "DoCreateCategoryRequest.name_max"
	ErrKeyDoUpdateCategoryRequestNameMax             = "DoUpdateCategoryRequest.name_max"
	ErrKeyDoUpdateAccountRequestNameMax              = "DoUpdateAccountRequest.name_max"
	ErrKeyCreateProductTypeRequestCodeMax            = "CreateProductTypeRequest.code_max"
	ErrKeyCreateProductTypeRequestCodeMin            = "CreateProductTypeRequest.code_min"
	ErrKeyCreateProductTypeRequestNameMax            = "CreateProductTypeRequest.name_max"
	ErrKeyDoGetSubLedgerAccountsRequestSearchByOneof = "DoGetSubLedgerAccountsRequest.searchBy_oneof"
	ErrKeyDatabaseError                              = "databaseError"
	ErrKeyUnableToGetData                            = "unableToGetData"
	ErrKeyUnableToCreateData                         = "unableToCreateData"
	ErrKeyFailedSubscribingKafka                     = "failedSubscribingKafka"
	ErrKeyFailedPublishToKafka                       = "failedPublishToKafka"
	ErrKeyFailedBindingPayload                       = "failedBindingPayload"
	ErrKeyFailedToCreateStorage                      = "failedToCreateStorage"
	ErrKeyBigQueryError                              = "bigQueryError"
	ErrKeyFailedFromExternalClient                   = "failedFromExternalClient"
	ErrKeyFailedGetFromCache                         = "failedGetFromCache"
	ErrKeyFailedSetToCache                           = "failedSetToCache"
	ErrKeyFailedUnmarshal                            = "failedUnmarshal"
	ErrKeyFailedMarshal                              = "failedMarshal"
	ErrKeyInvalidIgateMethod                         = "invalidIgateMethod"
	ErrKeyAccountNumberDifferentEntity               = "accountNumberDifferentEntity"
	ErrKeyTransactionIdsNotSync                      = "transactionIdsNotSync"
	ErrKeyAccountNumberNotFound                      = "accountNumberNotFound"
	ErrKeyLegacyIdNotFound                           = "legacyIdNotFound"
	ErrKeyAccountTypeNotValid                        = "accountTypeNotValid"
	ErrKeyCategoryCodeNotFound                       = "categoryCodeNotFound"
	ErrKeyCoaTypeNotFound                            = "coaTypeNotFound"
	ErrKeyCurrencyNotFound                           = "currencyNotFound"
	ErrKeyDataNotFound                               = "dataNotFound"
	ErrKeyEntityCodeNotFound                         = "entityCodeNotFound"
	ErrKeyProductTypeNotFound                        = "productTypeNotFound"
	ErrKeySubCategoryCodeNotFound                    = "subCategoryCodeNotFound"
	ErrKeyOwnerIdNotFound                            = "ownerIdNotFound"
	ErrKeyTransactionIdNotFound                      = "transactionIdNotFound"
	ErrKeyLoanPartnerAccountNotFound                 = "loanPartnerAccountNotFound"
	ErrKeyEntityNotFound                             = "entityNotFound"
	ErrKeyProductTypeCodeIsExist                     = "productTypeCodeIsExist"
	ErrKeyAccountTypeIsExist                         = "accountTypeIsExist"
	ErrKeyAltIdIsExist                               = "altIdIsExist"
	ErrKeyCategoryCodeIsExist                        = "categoryCodeIsExist"
	ErrKeyDataGlisExceedsTheLimit                    = "dataGLIsExceedsTheLimit"
	ErrKeyDataSubLedgerIsExceedsTheLimit             = "dataSubLedgerIsExceedsTheLimit"
	ErrKeyDataTrialBalanceDetailIsExceedsTheLimit    = "dataTrialBalanceDetailIsExceedsTheLimit"
	ErrKeyDataIsExist                                = "dataIsExist"
	ErrKeyEntityCodeIsExist                          = "entityCodeIsExist"
	ErrKeySubCategoryCodeIsExist                     = "subCategoryCodeIsExist"
	ErrKeyTransactionIdIsExist                       = "transactionIdIsExist"
	ErrKeyLegacyIdalreadyExists                      = "legacyIDAlreadyExists"
	ErrKeyJournalAccountIsExist                      = "journalAccountIsExist"
	ErrKeyAccountNumberIsExist                       = "accountNumberIsExist"
	ErrKeyAccountNumberRequired                      = "accountNumber_required"
	ErrKeyAccountTypeRequired                        = "accountType_required"
	ErrKeyAltIdRequired                              = "altId_required"
	ErrKeyCategoryCodeRequired                       = "categoryCode_required"
	ErrKeyCoaTypeCodeRequired                        = "coaTypeCode_required"
	ErrKeyCodeRequired                               = "code_required"
	ErrKeyCurrencyRequired                           = "currency_required"
	ErrKeyEndDateRequired                            = "endDate_required"
	ErrKeyEntityCodeRequired                         = "entityCode_required"
	ErrKeyNameRequired                               = "name_required"
	ErrKeyOwnerIdRequired                            = "ownerId_required"
	ErrKeyStartDateRequired                          = "startDate_required"
	ErrKeyStartDateAndEndDateRequiredIfOneIsFilled   = "startDateAndEndDateRequiredIfOneIsFilled"
	ErrKeyStatusRequired                             = "status_required"
	ErrKeySubCategoryCodeRequired                    = "subCategoryCode_required"
	ErrKeyMetadataRequired                           = "metadata_required"
	ErrKeyKeyRequired                                = "key_required"
	ErrKeyValueRequired                              = "value_required"
	ErrKeyReferenceNumberRequired                    = "referenceNumber_required"
	ErrKeyTransactionIdRequired                      = "transactionId_required"
	ErrKeyOrderTypeRequired                          = "orderType_required"
	ErrKeyTransactionDateRequired                    = "transactionDate_required"
	ErrKeyProcessingDateRequired                     = "processingDate_required"
	ErrKeyTransactionsRequired                       = "transactions_required"
	ErrKeyTransactionTypeRequired                    = "transactionType_required"
	ErrKeyTransactionTypeNameRequired                = "transactionTypeName_required"
	ErrKeyAccountRequired                            = "account_required"
	ErrKeyNarrativeRequired                          = "narrative_required"
	ErrKeyAmountRequired                             = "amount_required"
	ErrKeyIsDebitRequired                            = "isDebit_required"
	ErrKeySearchRequiredWith                         = "search_required_with"
	ErrKeyStartDateRequiredWith                      = "startDate_required_with"
	ErrKeyEndDateRequiredWith                        = "endDate_required_with"
	ErrKeyJobNameRequired                            = "jobName_required"
	ErrKeyPartnerIdRequired                          = "partnerId_required"
	ErrKeyPartnerNameRequired                        = "partnerName_required"
	ErrKeyLoanKindRequired                           = "loanKind_required"
	ErrKeyLoanSubCategoryCodeRequired                = "loanSubCategoryCode_required"
	ErrKeyAdjustmentDateRequired                     = "adjustmentDate_required"
	ErrKeyOwnerIdRequiredWithoutAll                  = "ownerId_required_without_all"
	ErrKeyAltIdRequiredWithoutAll                    = "altId_required_without_all"
	ErrKeyAccountNumbersRequiredWithoutAll           = "accountNumbers_required_without_all"
	ErrKeyAccountTypeRequiredWithoutAll              = "accountType_required_without_all"
	ErrKeyLoanKindRequiredWithoutAll                 = "loanKind_required_without_all"
	ErrKeyPartnerIdRequiredWithoutAll                = "partnerId_required_without_all"
	ErrKeyLoanSubCategoryCodeRequiredWithoutAll      = "loanSubCategoryCode_required_without_all"
	ErrKeyEntityCodeRequiredWithoutAll               = "entityCode_required_without_all"
	ErrKeyNameRequiredWithoutAll                     = "name_required_without_all"
	ErrKeyPartnerNameMaxnospace                      = "partnerName_maxnospace"
	ErrKeyPartnerNameMinnospace                      = "partnerName_minnospace"
	ErrKeyPartnerIdMaxnospace                        = "partnerId_maxnospace"
	ErrKeyCategoryCodeMax                            = "categoryCode_max"
	ErrKeyCategoryCodeMin                            = "categoryCode_min"
	ErrKeyCoaTypeCodeMax                             = "coaTypeCode_max"
	ErrKeyCoaTypeCodeMin                             = "coaTypeCode_min"
	ErrKeyCodeMax                                    = "code_max"
	ErrKeyCodeMin                                    = "code_min"
	ErrKeyCurrencyMax                                = "currency_max"
	ErrKeyCurrencyMin                                = "currency_min"
	ErrKeyDescriptionMax                             = "description_max"
	ErrKeyEntityCodeMax                              = "entityCode_max"
	ErrKeyEntityCodeMin                              = "entityCode_min"
	ErrKeyNameMax                                    = "name_max"
	ErrKeyOwnerIdMax                                 = "ownerId_max"
	ErrKeyOwnerIdMin                                 = "ownerId_min"
	ErrKeyProductTypeCodeMax                         = "productTypeCode_max"
	ErrKeyProductTypeCodeMin                         = "productTypeCode_min"
	ErrKeySubCategoryCodeMax                         = "subCategoryCode_max"
	ErrKeySubCategoryCodeMin                         = "subCategoryCode_min"
	ErrKeyAltIdAlphanumDashUscore                    = "altId_alphanumDashUscore"
	ErrKeyCategoryCodeNumeric                        = "categoryCode_numeric"
	ErrKeyCodeAlpha                                  = "code_alpha"
	ErrKeyCodeNumeric                                = "code_numeric"
	ErrKeyCurrencyAlpha                              = "currency_alpha"
	ErrKeyDateRangeMax31Days                         = "dateRangeMax31Days"
	ErrKeyEmailEmail                                 = "email_email"
	ErrKeyEndDateIsAfterToday                        = "endDateIsAfterToday"
	ErrKeyDateIsGreaterThanToday                     = "dateIsGreaterThanToday"
	ErrKeyEntityCodeNumeric                          = "entityCode_numeric"
	ErrKeyInvalidFormatAmount                        = "invalidFormatAmount"
	ErrKeyInvalidFormatDate                          = "invalidFormatDate"
	ErrKeyLimitMustBeGreaterThanZero                 = "limitMustBeGreaterThanZero"
	ErrKeyNameAlphanumericMix                        = "name_alphanumericMix"
	ErrKeyNameNospecial                              = "name_nospecial"
	ErrKeyNameNoStartEndSpaces                       = "name_noStartEndSpaces"
	ErrKeyNormalBalanceOneof                         = "normalBalance_oneof"
	ErrKeyOwnerIdAlphanum                            = "ownerId_alphanum"
	ErrKeyProductTypeCodeNumeric                     = "productTypeCode_numeric"
	ErrKeyStartDateAndEndDateEqualToday              = "startDateAndEndDateEqualToday"
	ErrKeyStartDateIsAfterEndDate                    = "startDateIsAfterEndDate"
	ErrKeyStatusOneof                                = "status_oneof"
	ErrKeySubCategoryCodeNumeric                     = "subCategoryCode_numeric"
	ErrKeyTransactionsEmpty                          = "transactionsEmpty"
	ErrKeySortOneof                                  = "sort_oneof"
	ErrKeySortByOneof                                = "sortBy_oneof"
	ErrKeySearchByOneof                              = "searchBy_oneof"
	ErrKeyJobNameOneof                               = "jobName_oneof"
	ErrKeyAccountTypeOneof                           = "accountType_oneof"
	ErrKeyBalanceSheetDateIsTodayOrLater             = "balanceSheetDateIsTodayOrLater"
	ErrKeyTransactionDateDatetime                    = "transactionDate_datetime"
	ErrKeyProcessingDateDatetime                     = "processingDate_datetime"
	ErrKeyClosedPeriodNotFound                       = "closedPeriodNotFound"
	ErrKeyPeriodAlreadyClosed                        = "periodAlreadyClosed"
)

const (
	ErrCodeInvalidLength         = "INVALID_LENGTH"
	ErrCodeInvalidValues         = "INVALID_VALUES"
	ErrCodeMissingField          = "MISSING_FIELD"
	ErrCodeDatabaseError         = "DATABASE_ERROR"
	ErrCodeInternalServerError   = "INTERNAL_SERVER_ERROR"
	ErrCodeUnexpectedError       = "UNEXPECTED_ERROR"
	ErrCodeBqError               = "BQ_ERROR"
	ErrCodeExternalServerError   = "EXTERNAL_SERVER_ERROR"
	ErrCodeCacheError            = "CACHE_ERROR"
	ErrCodeDataNotFound          = "DATA_NOT_FOUND"
	ErrCodeDataIsExist           = "DATA_IS_EXIST"
	ErrCodeDataIsExceedsLimit    = "DATA_IS_EXCEEDS_LIMIT"
	ErrCodeLegacyIdAlreadyExists = "LEGACY_ID_ALREADY_EXISTS"
)

var (
	errFieldCanHaveAMaximumLengthOf5Characters                                                                                                                           = errors.New("field can have a maximum length of 5 characters")
	errFieldMustBeAtLeast5Characters                                                                                                                                     = errors.New("field must be at least 5 characters")
	errFieldCanOnlyContainNumericValues                                                                                                                                  = errors.New("field can only contain numeric values")
	errFieldIsMissing                                                                                                                                                    = errors.New("field is missing")
	errFieldCanHaveAMaximumLengthOf100Characters                                                                                                                         = errors.New("field can have a maximum length of 100 characters")
	errFieldMustBeAtLeast3Characters                                                                                                                                     = errors.New("field must be at least 3 characters")
	errOneOfAccountNumberOrAltId                                                                                                                                         = errors.New("one of accountNumber or altId")
	errDatabaseError                                                                                                                                                     = errors.New("database error")
	errUnableToGetData                                                                                                                                                   = errors.New("unable to get data")
	errUnableToCreateData                                                                                                                                                = errors.New("unable to create data")
	errFailedSubscribingKafka                                                                                                                                            = errors.New("failed subscribing kafka")
	errFailedPublishMessageToKafka                                                                                                                                       = errors.New("failed publish message to kafka")
	errFailedBindingPayload                                                                                                                                              = errors.New("failed binding payload")
	errFailedToCreateStorage                                                                                                                                             = errors.New("failed to create storage")
	errBqError                                                                                                                                                           = errors.New("bq error")
	errFailedFromExternalClient                                                                                                                                          = errors.New("failed from external client ")
	errFailedGetFromCache                                                                                                                                                = errors.New("failed get from cache")
	errFailedSetToCache                                                                                                                                                  = errors.New("failed set to cache")
	errFailedJsonUnmarshal                                                                                                                                               = errors.New("failed json unmarshal")
	errFailedJsonMarshal                                                                                                                                                 = errors.New("failed json marshal")
	errInvalidIgateMethod                                                                                                                                                = errors.New("invalid igate method")
	errAccountNumberCannotBeADifferentEntity                                                                                                                             = errors.New("account number cannot be a different entity")
	errTransactionIdsIsNotInSync                                                                                                                                         = errors.New("transaction ids is not in sync")
	errAccountNumberNotFound                                                                                                                                             = errors.New("account number not found")
	errLegacyIdNotFound                                                                                                                                                  = errors.New("legacy id not found")
	errAccountTypeNotValid                                                                                                                                               = errors.New("account type not valid")
	errCategoryCodeNotFound                                                                                                                                              = errors.New("category code not found")
	errCoaTypeCodeNotFound                                                                                                                                               = errors.New("coa type code not found")
	errCurrencyNotFound                                                                                                                                                  = errors.New("currency not found")
	errDataNotFound                                                                                                                                                      = errors.New("data not found")
	errEntityCodeNotFound                                                                                                                                                = errors.New("entity code not found")
	errProductTypeCodeNotFound                                                                                                                                           = errors.New("product type code not found")
	errSubCategoryCodeNotFound                                                                                                                                           = errors.New("sub category code not found")
	errOwnerIdNotFound                                                                                                                                                   = errors.New("owner id not found")
	errTransactionIdNotFound                                                                                                                                             = errors.New("transaction id not found")
	errLoanPartnerAccountNotFound                                                                                                                                        = errors.New("loan partner account not found")
	errEntityNotFound                                                                                                                                                    = errors.New("entity not found")
	errProductTypeCodeIsExist                                                                                                                                            = errors.New("product type code is exist")
	errAccountTypeIsExist                                                                                                                                                = errors.New("account type is exist")
	errAlternateIdIsExist                                                                                                                                                = errors.New("alternate id is exist")
	errCategoryCodeIsExist                                                                                                                                               = errors.New("category code is exist")
	errTheDataIsTooBigAndWeWillSendACsvFileToYourEmail                                                                                                                   = errors.New("the data is too big and we will send a csv file to your email")
	errTheDataExceedsTheLimit                                                                                                                                            = errors.New("the data exceeds the limit")
	errDataIsExist                                                                                                                                                       = errors.New("data is exist")
	errEntityCodeIsExist                                                                                                                                                 = errors.New("entity code is exist")
	errSubCategoryCodeIsExist                                                                                                                                            = errors.New("sub category code is exist")
	errTransactionIdIsExist                                                                                                                                              = errors.New("transaction id is exist")
	errTheResourceCouldNotBeUpdatedBecauseTheLegacyIdAlreadyExists                                                                                                       = errors.New("the resource could not be updated because the legacy id already exists")
	errUnableToChangeTheEntityBecauseTheAccountHasATransactions                                                                                                          = errors.New("unable to change the entity because the account has a transactions")
	errAccountNumberIsExist                                                                                                                                              = errors.New("account number is exist")
	errStartDateOrEndDateMustBeFilledInIfEitherIsFilledIn                                                                                                                = errors.New("start date or end date must be filled in if either is filled in")
	errRequiredFieldsAtLeastOwnerId                                                                                                                                      = errors.New("required fields at least ownerId")
	errRequiredFieldsAtLeastAltId                                                                                                                                        = errors.New("required fields at least altId")
	errRequiredFieldsAtLeastAccountNumbers                                                                                                                               = errors.New("required fields at least accountNumbers")
	errRequiredFieldsAtLeastAccountType                                                                                                                                  = errors.New("required fields at least accountType")
	errRequiredFieldsAtLeastLoanKind                                                                                                                                     = errors.New("required fields at least loanKind")
	errRequiredFieldsAtLeastPartnerId                                                                                                                                    = errors.New("required fields at least partnerId")
	errRequiredFieldsAtLeastLoanSubCategoryCode                                                                                                                          = errors.New("required fields at least loanSubCategoryCode")
	errRequiredFieldsAtLeastEntityCode                                                                                                                                   = errors.New("required fields at least entityCode")
	errRequiredFieldsAtLeastName                                                                                                                                         = errors.New("required fields at least name")
	errFieldCanHaveAMaximumLengthOf55Characters                                                                                                                          = errors.New("field can have a maximum length of 55 characters")
	errFieldCanHaveAMinimumLengthOf4Characters                                                                                                                           = errors.New("field can have a minimum length of 4 characters")
	errFieldCanHaveAMaximumLengthOf15Characters                                                                                                                          = errors.New("field can have a maximum length of 15 characters")
	errFieldCanHaveAMaximumLengthOf3Characters                                                                                                                           = errors.New("field can have a maximum length of 3 characters")
	errFieldCanHaveAMaximumLengthOf50Characters                                                                                                                          = errors.New("field can have a maximum length of 50 characters")
	errFieldMustBeAtLeast1Characters                                                                                                                                     = errors.New("field must be at least 1 characters")
	errOnlyAcceptAlphanumericWithDashAndUnderscore                                                                                                                       = errors.New("only accept alphanumeric with dash (-) and underscore (_)")
	errFieldCanOnlyContainAlphaValues                                                                                                                                    = errors.New("field can only contain alpha values")
	errDateRangeMax31Days                                                                                                                                                = errors.New("date range max 31 days")
	errFormatEmailNotValid                                                                                                                                               = errors.New("format email not valid")
	errEndDateCannotBeLaterThanToday                                                                                                                                     = errors.New("end date cannot be later than today")
	errDateCannotBeGreaterThanToday                                                                                                                                      = errors.New("date cannot be greater than today")
	errInvalidFormatAmount                                                                                                                                               = errors.New("invalid format amount")
	errInvalidFormatDate                                                                                                                                                 = errors.New("invalid format date")
	errTheLimitMustBeGreaterThanZero                                                                                                                                     = errors.New("the limit must be greater than zero")
	errOnlyAcceptAlphanumericAndSomeSpecialCharacters                                                                                                                    = errors.New("only accept alphanumeric and some special characters")
	errInputFieldNoSpecialCharacters                                                                                                                                     = errors.New("input field no special characters")
	errFieldsShouldNotAcceptSpacesAtStartAndEndOfInput                                                                                                                   = errors.New("fields should not accept spaces at start and end of input")
	errOneOfDebitOrCredit                                                                                                                                                = errors.New("one of debit or credit")
	errFieldCanOnlyContainAlphanumericValues                                                                                                                             = errors.New("field can only contain alphanumeric values")
	errStartDateOrEndDateCannotBeTheSameAsToday                                                                                                                          = errors.New("start date or end date cannot be the same as today")
	errEndDateMustBeGreaterThanStartDate                                                                                                                                 = errors.New("end date must be greater than start date")
	errOneOfActiveOrInactive                                                                                                                                             = errors.New("one of active or inactive")
	errTransactionDataIsEmpty                                                                                                                                            = errors.New("transaction data is empty")
	errOneOfAscOrDesc                                                                                                                                                    = errors.New("one of asc or desc")
	errOneOfCreatedAtOrSubCategoryCode                                                                                                                                   = errors.New("one of createdAt or subCategoryCode")
	errOneOfAccountNumberOrAltIdOrOwnerId                                                                                                                                = errors.New("one of accountNumber or altId or ownerId")
	errInvalidJobName                                                                                                                                                    = errors.New("invalid job name")
	errOneOfCashInTransitDisburseCashInTransitRepaymentInternalAccountsRevenueAmarthaInternalAccountsAdminFeeAmarthaInternalAccountsPphAmarthaInternalAccountsPpnAmartha = errors.New("one of CASH_IN_TRANSIT_DISBURSE CASH_IN_TRANSIT_REPAYMENT INTERNAL_ACCOUNTS_REVENUE_AMARTHA INTERNAL_ACCOUNTS_ADMIN_FEE_AMARTHA INTERNAL_ACCOUNTS_PPH_AMARTHA INTERNAL_ACCOUNTS_PPN_AMARTHA")
	errBalanceSheetDateCannotBeTodayOrLaterThanToday                                                                                                                     = errors.New("balance sheet date cannot be today or later than today")
	errFormatMustBe20060102150405                                                                                                                                        = errors.New("format must be 2006-01-02 15:04:05")
	errClosedPeriodNotFound                                                                                                                                              = errors.New("closed period not found")
	errPeriodAlreadyClosed                                                                                                                                               = errors.New("period already closed")
)

var MapErrors = MapErrs{
	ErrKeyCreateSubCategoryRequestCodeMax: ErrorDetail{
		Code:         ErrCodeInvalidLength,
		ErrorMessage: errFieldCanHaveAMaximumLengthOf5Characters,
	},
	ErrKeyCreateSubCategoryRequestCodeMin: ErrorDetail{
		Code:         ErrCodeInvalidLength,
		ErrorMessage: errFieldMustBeAtLeast5Characters,
	},
	ErrKeyCreateSubCategoryRequestCodeNumeric: ErrorDetail{
		Code:         ErrCodeInvalidValues,
		ErrorMessage: errFieldCanOnlyContainNumericValues,
	},
	ErrKeyCreateSubCategoryRequestCodeRequired: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errFieldIsMissing,
	},
	ErrKeyCreateSubCategoryRequestNameMax: ErrorDetail{
		Code:         ErrCodeInvalidLength,
		ErrorMessage: errFieldCanHaveAMaximumLengthOf100Characters,
	},
	ErrKeyUpdateSubCategoryRequestNameMax: ErrorDetail{
		Code:         ErrCodeInvalidLength,
		ErrorMessage: errFieldCanHaveAMaximumLengthOf100Characters,
	},
	ErrKeyDoCreateAccountRequestNameMax: ErrorDetail{
		Code:         ErrCodeInvalidLength,
		ErrorMessage: errFieldCanHaveAMaximumLengthOf100Characters,
	},
	ErrKeyDoCreateCategoryRequestNameMax: ErrorDetail{
		Code:         ErrCodeInvalidLength,
		ErrorMessage: errFieldCanHaveAMaximumLengthOf100Characters,
	},
	ErrKeyDoUpdateCategoryRequestNameMax: ErrorDetail{
		Code:         ErrCodeInvalidLength,
		ErrorMessage: errFieldCanHaveAMaximumLengthOf100Characters,
	},
	ErrKeyDoUpdateAccountRequestNameMax: ErrorDetail{
		Code:         ErrCodeInvalidLength,
		ErrorMessage: errFieldCanHaveAMaximumLengthOf100Characters,
	},
	ErrKeyCreateProductTypeRequestCodeMax: ErrorDetail{
		Code:         ErrCodeInvalidLength,
		ErrorMessage: errFieldCanHaveAMaximumLengthOf5Characters,
	},
	ErrKeyCreateProductTypeRequestCodeMin: ErrorDetail{
		Code:         ErrCodeInvalidLength,
		ErrorMessage: errFieldMustBeAtLeast3Characters,
	},
	ErrKeyCreateProductTypeRequestNameMax: ErrorDetail{
		Code:         ErrCodeInvalidLength,
		ErrorMessage: errFieldCanHaveAMaximumLengthOf100Characters,
	},
	ErrKeyDoGetSubLedgerAccountsRequestSearchByOneof: ErrorDetail{
		Code:         ErrCodeInvalidValues,
		ErrorMessage: errOneOfAccountNumberOrAltId,
	},
	ErrKeyDatabaseError: ErrorDetail{
		Code:         ErrCodeDatabaseError,
		ErrorMessage: errDatabaseError,
	},
	ErrKeyUnableToGetData: ErrorDetail{
		Code:         ErrCodeInternalServerError,
		ErrorMessage: errUnableToGetData,
	},
	ErrKeyUnableToCreateData: ErrorDetail{
		Code:         ErrCodeInternalServerError,
		ErrorMessage: errUnableToCreateData,
	},
	ErrKeyFailedSubscribingKafka: ErrorDetail{
		Code:         ErrCodeInternalServerError,
		ErrorMessage: errFailedSubscribingKafka,
	},
	ErrKeyFailedPublishToKafka: ErrorDetail{
		Code:         ErrCodeInternalServerError,
		ErrorMessage: errFailedPublishMessageToKafka,
	},
	ErrKeyFailedBindingPayload: ErrorDetail{
		Code:         ErrCodeUnexpectedError,
		ErrorMessage: errFailedBindingPayload,
	},
	ErrKeyFailedToCreateStorage: ErrorDetail{
		Code:         ErrCodeInternalServerError,
		ErrorMessage: errFailedToCreateStorage,
	},
	ErrKeyBigQueryError: ErrorDetail{
		Code:         ErrCodeBqError,
		ErrorMessage: errBqError,
	},
	ErrKeyFailedFromExternalClient: ErrorDetail{
		Code:         ErrCodeExternalServerError,
		ErrorMessage: errFailedFromExternalClient,
	},
	ErrKeyFailedGetFromCache: ErrorDetail{
		Code:         ErrCodeCacheError,
		ErrorMessage: errFailedGetFromCache,
	},
	ErrKeyFailedSetToCache: ErrorDetail{
		Code:         ErrCodeCacheError,
		ErrorMessage: errFailedSetToCache,
	},
	ErrKeyFailedUnmarshal: ErrorDetail{
		Code:         ErrCodeInvalidValues,
		ErrorMessage: errFailedJsonUnmarshal,
	},
	ErrKeyFailedMarshal: ErrorDetail{
		Code:         ErrCodeInvalidValues,
		ErrorMessage: errFailedJsonMarshal,
	},
	ErrKeyInvalidIgateMethod: ErrorDetail{
		Code:         ErrCodeInvalidValues,
		ErrorMessage: errInvalidIgateMethod,
	},
	ErrKeyAccountNumberDifferentEntity: ErrorDetail{
		Code:         ErrCodeInvalidValues,
		ErrorMessage: errAccountNumberCannotBeADifferentEntity,
	},
	ErrKeyTransactionIdsNotSync: ErrorDetail{
		Code:         ErrCodeInvalidValues,
		ErrorMessage: errTransactionIdsIsNotInSync,
	},
	ErrKeyAccountNumberNotFound: ErrorDetail{
		Code:         ErrCodeDataNotFound,
		ErrorMessage: errAccountNumberNotFound,
	},
	ErrKeyLegacyIdNotFound: ErrorDetail{
		Code:         ErrCodeDataNotFound,
		ErrorMessage: errLegacyIdNotFound,
	},
	ErrKeyAccountTypeNotValid: ErrorDetail{
		Code:         ErrCodeDataNotFound,
		ErrorMessage: errAccountTypeNotValid,
	},
	ErrKeyCategoryCodeNotFound: ErrorDetail{
		Code:         ErrCodeDataNotFound,
		ErrorMessage: errCategoryCodeNotFound,
	},
	ErrKeyCoaTypeNotFound: ErrorDetail{
		Code:         ErrCodeDataNotFound,
		ErrorMessage: errCoaTypeCodeNotFound,
	},
	ErrKeyCurrencyNotFound: ErrorDetail{
		Code:         ErrCodeDataNotFound,
		ErrorMessage: errCurrencyNotFound,
	},
	ErrKeyDataNotFound: ErrorDetail{
		Code:         ErrCodeDataNotFound,
		ErrorMessage: errDataNotFound,
	},
	ErrKeyEntityCodeNotFound: ErrorDetail{
		Code:         ErrCodeDataNotFound,
		ErrorMessage: errEntityCodeNotFound,
	},
	ErrKeyProductTypeNotFound: ErrorDetail{
		Code:         ErrCodeDataNotFound,
		ErrorMessage: errProductTypeCodeNotFound,
	},
	ErrKeySubCategoryCodeNotFound: ErrorDetail{
		Code:         ErrCodeDataNotFound,
		ErrorMessage: errSubCategoryCodeNotFound,
	},
	ErrKeyOwnerIdNotFound: ErrorDetail{
		Code:         ErrCodeDataNotFound,
		ErrorMessage: errOwnerIdNotFound,
	},
	ErrKeyTransactionIdNotFound: ErrorDetail{
		Code:         ErrCodeDataNotFound,
		ErrorMessage: errTransactionIdNotFound,
	},
	ErrKeyLoanPartnerAccountNotFound: ErrorDetail{
		Code:         ErrCodeDataNotFound,
		ErrorMessage: errLoanPartnerAccountNotFound,
	},
	ErrKeyEntityNotFound: ErrorDetail{
		Code:         ErrCodeDataNotFound,
		ErrorMessage: errEntityNotFound,
	},
	ErrKeyProductTypeCodeIsExist: ErrorDetail{
		Code:         ErrCodeDataIsExist,
		ErrorMessage: errProductTypeCodeIsExist,
	},
	ErrKeyAccountTypeIsExist: ErrorDetail{
		Code:         ErrCodeDataIsExist,
		ErrorMessage: errAccountTypeIsExist,
	},
	ErrKeyAltIdIsExist: ErrorDetail{
		Code:         ErrCodeDataIsExist,
		ErrorMessage: errAlternateIdIsExist,
	},
	ErrKeyCategoryCodeIsExist: ErrorDetail{
		Code:         ErrCodeDataIsExist,
		ErrorMessage: errCategoryCodeIsExist,
	},
	ErrKeyDataGlisExceedsTheLimit: ErrorDetail{
		Code:         ErrCodeDataIsExceedsLimit,
		ErrorMessage: errTheDataIsTooBigAndWeWillSendACsvFileToYourEmail,
	},
	ErrKeyDataSubLedgerIsExceedsTheLimit: ErrorDetail{
		Code:         ErrCodeDataIsExceedsLimit,
		ErrorMessage: errTheDataExceedsTheLimit,
	},
	ErrKeyDataTrialBalanceDetailIsExceedsTheLimit: ErrorDetail{
		Code:         ErrCodeDataIsExceedsLimit,
		ErrorMessage: errTheDataExceedsTheLimit,
	},
	ErrKeyDataIsExist: ErrorDetail{
		Code:         ErrCodeDataIsExist,
		ErrorMessage: errDataIsExist,
	},
	ErrKeyEntityCodeIsExist: ErrorDetail{
		Code:         ErrCodeDataIsExist,
		ErrorMessage: errEntityCodeIsExist,
	},
	ErrKeySubCategoryCodeIsExist: ErrorDetail{
		Code:         ErrCodeDataIsExist,
		ErrorMessage: errSubCategoryCodeIsExist,
	},
	ErrKeyTransactionIdIsExist: ErrorDetail{
		Code:         ErrCodeDataIsExist,
		ErrorMessage: errTransactionIdIsExist,
	},
	ErrKeyLegacyIdalreadyExists: ErrorDetail{
		Code:         ErrCodeLegacyIdAlreadyExists,
		ErrorMessage: errTheResourceCouldNotBeUpdatedBecauseTheLegacyIdAlreadyExists,
	},
	ErrKeyJournalAccountIsExist: ErrorDetail{
		Code:         ErrCodeDataIsExist,
		ErrorMessage: errUnableToChangeTheEntityBecauseTheAccountHasATransactions,
	},
	ErrKeyAccountNumberIsExist: ErrorDetail{
		Code:         ErrCodeDataIsExist,
		ErrorMessage: errAccountNumberIsExist,
	},
	ErrKeyAccountNumberRequired: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errFieldIsMissing,
	},
	ErrKeyAccountTypeRequired: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errFieldIsMissing,
	},
	ErrKeyAltIdRequired: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errFieldIsMissing,
	},
	ErrKeyCategoryCodeRequired: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errFieldIsMissing,
	},
	ErrKeyCoaTypeCodeRequired: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errFieldIsMissing,
	},
	ErrKeyCodeRequired: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errFieldIsMissing,
	},
	ErrKeyCurrencyRequired: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errFieldIsMissing,
	},
	ErrKeyEndDateRequired: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errFieldIsMissing,
	},
	ErrKeyEntityCodeRequired: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errFieldIsMissing,
	},
	ErrKeyNameRequired: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errFieldIsMissing,
	},
	ErrKeyOwnerIdRequired: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errFieldIsMissing,
	},
	ErrKeyStartDateRequired: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errFieldIsMissing,
	},
	ErrKeyStartDateAndEndDateRequiredIfOneIsFilled: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errStartDateOrEndDateMustBeFilledInIfEitherIsFilledIn,
	},
	ErrKeyStatusRequired: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errFieldIsMissing,
	},
	ErrKeySubCategoryCodeRequired: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errFieldIsMissing,
	},
	ErrKeyMetadataRequired: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errFieldIsMissing,
	},
	ErrKeyKeyRequired: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errFieldIsMissing,
	},
	ErrKeyValueRequired: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errFieldIsMissing,
	},
	ErrKeyReferenceNumberRequired: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errFieldIsMissing,
	},
	ErrKeyTransactionIdRequired: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errFieldIsMissing,
	},
	ErrKeyOrderTypeRequired: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errFieldIsMissing,
	},
	ErrKeyTransactionDateRequired: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errFieldIsMissing,
	},
	ErrKeyProcessingDateRequired: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errFieldIsMissing,
	},
	ErrKeyTransactionsRequired: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errFieldIsMissing,
	},
	ErrKeyTransactionTypeRequired: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errFieldIsMissing,
	},
	ErrKeyTransactionTypeNameRequired: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errFieldIsMissing,
	},
	ErrKeyAccountRequired: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errFieldIsMissing,
	},
	ErrKeyNarrativeRequired: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errFieldIsMissing,
	},
	ErrKeyAmountRequired: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errFieldIsMissing,
	},
	ErrKeyIsDebitRequired: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errFieldIsMissing,
	},
	ErrKeySearchRequiredWith: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errFieldIsMissing,
	},
	ErrKeyStartDateRequiredWith: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errFieldIsMissing,
	},
	ErrKeyEndDateRequiredWith: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errFieldIsMissing,
	},
	ErrKeyJobNameRequired: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errFieldIsMissing,
	},
	ErrKeyPartnerIdRequired: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errFieldIsMissing,
	},
	ErrKeyPartnerNameRequired: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errFieldIsMissing,
	},
	ErrKeyLoanKindRequired: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errFieldIsMissing,
	},
	ErrKeyLoanSubCategoryCodeRequired: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errFieldIsMissing,
	},
	ErrKeyAdjustmentDateRequired: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errFieldIsMissing,
	},
	ErrKeyOwnerIdRequiredWithoutAll: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errRequiredFieldsAtLeastOwnerId,
	},
	ErrKeyAltIdRequiredWithoutAll: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errRequiredFieldsAtLeastAltId,
	},
	ErrKeyAccountNumbersRequiredWithoutAll: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errRequiredFieldsAtLeastAccountNumbers,
	},
	ErrKeyAccountTypeRequiredWithoutAll: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errRequiredFieldsAtLeastAccountType,
	},
	ErrKeyLoanKindRequiredWithoutAll: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errRequiredFieldsAtLeastLoanKind,
	},
	ErrKeyPartnerIdRequiredWithoutAll: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errRequiredFieldsAtLeastPartnerId,
	},
	ErrKeyLoanSubCategoryCodeRequiredWithoutAll: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errRequiredFieldsAtLeastLoanSubCategoryCode,
	},
	ErrKeyEntityCodeRequiredWithoutAll: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errRequiredFieldsAtLeastEntityCode,
	},
	ErrKeyNameRequiredWithoutAll: ErrorDetail{
		Code:         ErrCodeMissingField,
		ErrorMessage: errRequiredFieldsAtLeastName,
	},
	ErrKeyPartnerNameMaxnospace: ErrorDetail{
		Code:         ErrCodeInvalidLength,
		ErrorMessage: errFieldCanHaveAMaximumLengthOf55Characters,
	},
	ErrKeyPartnerNameMinnospace: ErrorDetail{
		Code:         ErrCodeInvalidLength,
		ErrorMessage: errFieldCanHaveAMinimumLengthOf4Characters,
	},
	ErrKeyPartnerIdMaxnospace: ErrorDetail{
		Code:         ErrCodeInvalidLength,
		ErrorMessage: errFieldCanHaveAMaximumLengthOf15Characters,
	},
	ErrKeyCategoryCodeMax: ErrorDetail{
		Code:         ErrCodeInvalidLength,
		ErrorMessage: errFieldCanHaveAMaximumLengthOf3Characters,
	},
	ErrKeyCategoryCodeMin: ErrorDetail{
		Code:         ErrCodeInvalidLength,
		ErrorMessage: errFieldMustBeAtLeast3Characters,
	},
	ErrKeyCoaTypeCodeMax: ErrorDetail{
		Code:         ErrCodeInvalidLength,
		ErrorMessage: errFieldCanHaveAMaximumLengthOf3Characters,
	},
	ErrKeyCoaTypeCodeMin: ErrorDetail{
		Code:         ErrCodeInvalidLength,
		ErrorMessage: errFieldMustBeAtLeast3Characters,
	},
	ErrKeyCodeMax: ErrorDetail{
		Code:         ErrCodeInvalidLength,
		ErrorMessage: errFieldCanHaveAMaximumLengthOf3Characters,
	},
	ErrKeyCodeMin: ErrorDetail{
		Code:         ErrCodeInvalidLength,
		ErrorMessage: errFieldMustBeAtLeast3Characters,
	},
	ErrKeyCurrencyMax: ErrorDetail{
		Code:         ErrCodeInvalidLength,
		ErrorMessage: errFieldCanHaveAMaximumLengthOf3Characters,
	},
	ErrKeyCurrencyMin: ErrorDetail{
		Code:         ErrCodeInvalidLength,
		ErrorMessage: errFieldMustBeAtLeast3Characters,
	},
	ErrKeyDescriptionMax: ErrorDetail{
		Code:         ErrCodeInvalidLength,
		ErrorMessage: errFieldCanHaveAMaximumLengthOf50Characters,
	},
	ErrKeyEntityCodeMax: ErrorDetail{
		Code:         ErrCodeInvalidLength,
		ErrorMessage: errFieldCanHaveAMaximumLengthOf3Characters,
	},
	ErrKeyEntityCodeMin: ErrorDetail{
		Code:         ErrCodeInvalidLength,
		ErrorMessage: errFieldMustBeAtLeast3Characters,
	},
	ErrKeyNameMax: ErrorDetail{
		Code:         ErrCodeInvalidLength,
		ErrorMessage: errFieldCanHaveAMaximumLengthOf50Characters,
	},
	ErrKeyOwnerIdMax: ErrorDetail{
		Code:         ErrCodeInvalidLength,
		ErrorMessage: errFieldCanHaveAMaximumLengthOf15Characters,
	},
	ErrKeyOwnerIdMin: ErrorDetail{
		Code:         ErrCodeInvalidLength,
		ErrorMessage: errFieldMustBeAtLeast1Characters,
	},
	ErrKeyProductTypeCodeMax: ErrorDetail{
		Code:         ErrCodeInvalidLength,
		ErrorMessage: errFieldCanHaveAMaximumLengthOf5Characters,
	},
	ErrKeyProductTypeCodeMin: ErrorDetail{
		Code:         ErrCodeInvalidLength,
		ErrorMessage: errFieldMustBeAtLeast3Characters,
	},
	ErrKeySubCategoryCodeMax: ErrorDetail{
		Code:         ErrCodeInvalidLength,
		ErrorMessage: errFieldCanHaveAMaximumLengthOf5Characters,
	},
	ErrKeySubCategoryCodeMin: ErrorDetail{
		Code:         ErrCodeInvalidLength,
		ErrorMessage: errFieldMustBeAtLeast5Characters,
	},
	ErrKeyAltIdAlphanumDashUscore: ErrorDetail{
		Code:         ErrCodeInvalidValues,
		ErrorMessage: errOnlyAcceptAlphanumericWithDashAndUnderscore,
	},
	ErrKeyCategoryCodeNumeric: ErrorDetail{
		Code:         ErrCodeInvalidValues,
		ErrorMessage: errFieldCanOnlyContainNumericValues,
	},
	ErrKeyCodeAlpha: ErrorDetail{
		Code:         ErrCodeInvalidValues,
		ErrorMessage: errFieldCanOnlyContainAlphaValues,
	},
	ErrKeyCodeNumeric: ErrorDetail{
		Code:         ErrCodeInvalidValues,
		ErrorMessage: errFieldCanOnlyContainAlphaValues,
	},
	ErrKeyCurrencyAlpha: ErrorDetail{
		Code:         ErrCodeInvalidValues,
		ErrorMessage: errFieldCanOnlyContainAlphaValues,
	},
	ErrKeyDateRangeMax31Days: ErrorDetail{
		Code:         ErrCodeInvalidValues,
		ErrorMessage: errDateRangeMax31Days,
	},
	ErrKeyEmailEmail: ErrorDetail{
		Code:         ErrCodeInvalidValues,
		ErrorMessage: errFormatEmailNotValid,
	},
	ErrKeyEndDateIsAfterToday: ErrorDetail{
		Code:         ErrCodeInvalidValues,
		ErrorMessage: errEndDateCannotBeLaterThanToday,
	},
	ErrKeyDateIsGreaterThanToday: ErrorDetail{
		Code:         ErrCodeInvalidValues,
		ErrorMessage: errDateCannotBeGreaterThanToday,
	},
	ErrKeyEntityCodeNumeric: ErrorDetail{
		Code:         ErrCodeInvalidValues,
		ErrorMessage: errFieldCanOnlyContainNumericValues,
	},
	ErrKeyInvalidFormatAmount: ErrorDetail{
		Code:         ErrCodeInvalidValues,
		ErrorMessage: errInvalidFormatAmount,
	},
	ErrKeyInvalidFormatDate: ErrorDetail{
		Code:         ErrCodeInvalidValues,
		ErrorMessage: errInvalidFormatDate,
	},
	ErrKeyLimitMustBeGreaterThanZero: ErrorDetail{
		Code:         ErrCodeInvalidValues,
		ErrorMessage: errTheLimitMustBeGreaterThanZero,
	},
	ErrKeyNameAlphanumericMix: ErrorDetail{
		Code:         ErrCodeInvalidValues,
		ErrorMessage: errOnlyAcceptAlphanumericAndSomeSpecialCharacters,
	},
	ErrKeyNameNospecial: ErrorDetail{
		Code:         ErrCodeInvalidValues,
		ErrorMessage: errInputFieldNoSpecialCharacters,
	},
	ErrKeyNameNoStartEndSpaces: ErrorDetail{
		Code:         ErrCodeInvalidValues,
		ErrorMessage: errFieldsShouldNotAcceptSpacesAtStartAndEndOfInput,
	},
	ErrKeyNormalBalanceOneof: ErrorDetail{
		Code:         ErrCodeInvalidValues,
		ErrorMessage: errOneOfDebitOrCredit,
	},
	ErrKeyOwnerIdAlphanum: ErrorDetail{
		Code:         ErrCodeInvalidValues,
		ErrorMessage: errFieldCanOnlyContainAlphanumericValues,
	},
	ErrKeyProductTypeCodeNumeric: ErrorDetail{
		Code:         ErrCodeInvalidValues,
		ErrorMessage: errFieldCanOnlyContainNumericValues,
	},
	ErrKeyStartDateAndEndDateEqualToday: ErrorDetail{
		Code:         ErrCodeInvalidValues,
		ErrorMessage: errStartDateOrEndDateCannotBeTheSameAsToday,
	},
	ErrKeyStartDateIsAfterEndDate: ErrorDetail{
		Code:         ErrCodeInvalidValues,
		ErrorMessage: errEndDateMustBeGreaterThanStartDate,
	},
	ErrKeyStatusOneof: ErrorDetail{
		Code:         ErrCodeInvalidValues,
		ErrorMessage: errOneOfActiveOrInactive,
	},
	ErrKeySubCategoryCodeNumeric: ErrorDetail{
		Code:         ErrCodeInvalidValues,
		ErrorMessage: errFieldCanOnlyContainNumericValues,
	},
	ErrKeyTransactionsEmpty: ErrorDetail{
		Code:         ErrCodeInvalidValues,
		ErrorMessage: errTransactionDataIsEmpty,
	},
	ErrKeySortOneof: ErrorDetail{
		Code:         ErrCodeInvalidValues,
		ErrorMessage: errOneOfAscOrDesc,
	},
	ErrKeySortByOneof: ErrorDetail{
		Code:         ErrCodeInvalidValues,
		ErrorMessage: errOneOfCreatedAtOrSubCategoryCode,
	},
	ErrKeySearchByOneof: ErrorDetail{
		Code:         ErrCodeInvalidValues,
		ErrorMessage: errOneOfAccountNumberOrAltIdOrOwnerId,
	},
	ErrKeyJobNameOneof: ErrorDetail{
		Code:         ErrCodeInvalidValues,
		ErrorMessage: errInvalidJobName,
	},
	ErrKeyAccountTypeOneof: ErrorDetail{
		Code:         ErrCodeInvalidValues,
		ErrorMessage: errOneOfCashInTransitDisburseCashInTransitRepaymentInternalAccountsRevenueAmarthaInternalAccountsAdminFeeAmarthaInternalAccountsPphAmarthaInternalAccountsPpnAmartha,
	},
	ErrKeyBalanceSheetDateIsTodayOrLater: ErrorDetail{
		Code:         ErrCodeInvalidValues,
		ErrorMessage: errBalanceSheetDateCannotBeTodayOrLaterThanToday,
	},
	ErrKeyTransactionDateDatetime: ErrorDetail{
		Code:         ErrCodeInvalidValues,
		ErrorMessage: errFormatMustBe20060102150405,
	},
	ErrKeyProcessingDateDatetime: ErrorDetail{
		Code:         ErrCodeInvalidValues,
		ErrorMessage: errFormatMustBe20060102150405,
	},
	ErrKeyClosedPeriodNotFound: ErrorDetail{
		Code:         ErrCodeDataNotFound,
		ErrorMessage: errClosedPeriodNotFound,
	},
	ErrKeyPeriodAlreadyClosed: ErrorDetail{
		Code:         ErrCodeDataNotFound,
		ErrorMessage: errPeriodAlreadyClosed,
	},
}
