// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repositories/mysql/mysql_main.go
//
// Generated by this command:
//
//	mockgen -source=./internal/repositories/mysql/mysql_main.go -destination=./internal/repositories/mysql/mock/mysql_main_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "bitbucket.org/Amartha/go-accounting/internal/models"
	mysql "bitbucket.org/Amartha/go-accounting/internal/repositories/mysql"
	gomock "go.uber.org/mock/gomock"
)

// MockSQLRepository is a mock of SQLRepository interface.
type MockSQLRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSQLRepositoryMockRecorder
	isgomock struct{}
}

// MockSQLRepositoryMockRecorder is the mock recorder for MockSQLRepository.
type MockSQLRepositoryMockRecorder struct {
	mock *MockSQLRepository
}

// NewMockSQLRepository creates a new mock instance.
func NewMockSQLRepository(ctrl *gomock.Controller) *MockSQLRepository {
	mock := &MockSQLRepository{ctrl: ctrl}
	mock.recorder = &MockSQLRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSQLRepository) EXPECT() *MockSQLRepositoryMockRecorder {
	return m.recorder
}

// Atomic mocks base method.
func (m *MockSQLRepository) Atomic(ctx context.Context, steps func(context.Context, mysql.SQLRepository) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Atomic", ctx, steps)
	ret0, _ := ret[0].(error)
	return ret0
}

// Atomic indicates an expected call of Atomic.
func (mr *MockSQLRepositoryMockRecorder) Atomic(ctx, steps any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Atomic", reflect.TypeOf((*MockSQLRepository)(nil).Atomic), ctx, steps)
}

// CheckAccountTrialBalanceExist mocks base method.
func (m *MockSQLRepository) CheckAccountTrialBalanceExist(ctx context.Context, entityCode, subCategoryCode string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAccountTrialBalanceExist", ctx, entityCode, subCategoryCode)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckAccountTrialBalanceExist indicates an expected call of CheckAccountTrialBalanceExist.
func (mr *MockSQLRepositoryMockRecorder) CheckAccountTrialBalanceExist(ctx, entityCode, subCategoryCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAccountTrialBalanceExist", reflect.TypeOf((*MockSQLRepository)(nil).CheckAccountTrialBalanceExist), ctx, entityCode, subCategoryCode)
}

// GetAccountRepository mocks base method.
func (m *MockSQLRepository) GetAccountRepository() mysql.AccountRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountRepository")
	ret0, _ := ret[0].(mysql.AccountRepository)
	return ret0
}

// GetAccountRepository indicates an expected call of GetAccountRepository.
func (mr *MockSQLRepositoryMockRecorder) GetAccountRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountRepository", reflect.TypeOf((*MockSQLRepository)(nil).GetAccountRepository))
}

// GetAccountingRepository mocks base method.
func (m *MockSQLRepository) GetAccountingRepository() mysql.AccountingRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountingRepository")
	ret0, _ := ret[0].(mysql.AccountingRepository)
	return ret0
}

// GetAccountingRepository indicates an expected call of GetAccountingRepository.
func (mr *MockSQLRepositoryMockRecorder) GetAccountingRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountingRepository", reflect.TypeOf((*MockSQLRepository)(nil).GetAccountingRepository))
}

// GetAllCategorySubCategoryCOAType mocks base method.
func (m *MockSQLRepository) GetAllCategorySubCategoryCOAType(ctx context.Context) (map[string][]models.CategorySubCategoryCOAType, map[string][]models.CategorySubCategoryCOAType, map[string]models.CategorySubCategoryCOAType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCategorySubCategoryCOAType", ctx)
	ret0, _ := ret[0].(map[string][]models.CategorySubCategoryCOAType)
	ret1, _ := ret[1].(map[string][]models.CategorySubCategoryCOAType)
	ret2, _ := ret[2].(map[string]models.CategorySubCategoryCOAType)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetAllCategorySubCategoryCOAType indicates an expected call of GetAllCategorySubCategoryCOAType.
func (mr *MockSQLRepositoryMockRecorder) GetAllCategorySubCategoryCOAType(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCategorySubCategoryCOAType", reflect.TypeOf((*MockSQLRepository)(nil).GetAllCategorySubCategoryCOAType), ctx)
}

// GetCOATypeRepository mocks base method.
func (m *MockSQLRepository) GetCOATypeRepository() mysql.COATypeRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCOATypeRepository")
	ret0, _ := ret[0].(mysql.COATypeRepository)
	return ret0
}

// GetCOATypeRepository indicates an expected call of GetCOATypeRepository.
func (mr *MockSQLRepositoryMockRecorder) GetCOATypeRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCOATypeRepository", reflect.TypeOf((*MockSQLRepository)(nil).GetCOATypeRepository))
}

// GetCategoryRepository mocks base method.
func (m *MockSQLRepository) GetCategoryRepository() mysql.CategoryRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryRepository")
	ret0, _ := ret[0].(mysql.CategoryRepository)
	return ret0
}

// GetCategoryRepository indicates an expected call of GetCategoryRepository.
func (mr *MockSQLRepositoryMockRecorder) GetCategoryRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryRepository", reflect.TypeOf((*MockSQLRepository)(nil).GetCategoryRepository))
}

// GetEntityRepository mocks base method.
func (m *MockSQLRepository) GetEntityRepository() mysql.EntityRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntityRepository")
	ret0, _ := ret[0].(mysql.EntityRepository)
	return ret0
}

// GetEntityRepository indicates an expected call of GetEntityRepository.
func (mr *MockSQLRepositoryMockRecorder) GetEntityRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEntityRepository", reflect.TypeOf((*MockSQLRepository)(nil).GetEntityRepository))
}

// GetLoanPartnerAccountRepository mocks base method.
func (m *MockSQLRepository) GetLoanPartnerAccountRepository() mysql.LoanPartnerAccountRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoanPartnerAccountRepository")
	ret0, _ := ret[0].(mysql.LoanPartnerAccountRepository)
	return ret0
}

// GetLoanPartnerAccountRepository indicates an expected call of GetLoanPartnerAccountRepository.
func (mr *MockSQLRepositoryMockRecorder) GetLoanPartnerAccountRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoanPartnerAccountRepository", reflect.TypeOf((*MockSQLRepository)(nil).GetLoanPartnerAccountRepository))
}

// GetProductTypeRepository mocks base method.
func (m *MockSQLRepository) GetProductTypeRepository() mysql.ProductTypeRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductTypeRepository")
	ret0, _ := ret[0].(mysql.ProductTypeRepository)
	return ret0
}

// GetProductTypeRepository indicates an expected call of GetProductTypeRepository.
func (mr *MockSQLRepositoryMockRecorder) GetProductTypeRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductTypeRepository", reflect.TypeOf((*MockSQLRepository)(nil).GetProductTypeRepository))
}

// GetSubCategoryRepository mocks base method.
func (m *MockSQLRepository) GetSubCategoryRepository() mysql.SubCategoryRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubCategoryRepository")
	ret0, _ := ret[0].(mysql.SubCategoryRepository)
	return ret0
}

// GetSubCategoryRepository indicates an expected call of GetSubCategoryRepository.
func (mr *MockSQLRepositoryMockRecorder) GetSubCategoryRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubCategoryRepository", reflect.TypeOf((*MockSQLRepository)(nil).GetSubCategoryRepository))
}

// GetTrialBalanceRepository mocks base method.
func (m *MockSQLRepository) GetTrialBalanceRepository() mysql.TrialBalanceRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrialBalanceRepository")
	ret0, _ := ret[0].(mysql.TrialBalanceRepository)
	return ret0
}

// GetTrialBalanceRepository indicates an expected call of GetTrialBalanceRepository.
func (mr *MockSQLRepositoryMockRecorder) GetTrialBalanceRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrialBalanceRepository", reflect.TypeOf((*MockSQLRepository)(nil).GetTrialBalanceRepository))
}

// Ping mocks base method.
func (m *MockSQLRepository) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockSQLRepositoryMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockSQLRepository)(nil).Ping), ctx)
}
