// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repositories/mysql/mysql_loan_partner_account.go
//
// Generated by this command:
//
//	mockgen -source=./internal/repositories/mysql/mysql_loan_partner_account.go -destination=./internal/repositories/mysql/mock/mysql_loan_partner_account_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "bitbucket.org/Amartha/go-accounting/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockLoanPartnerAccountRepository is a mock of LoanPartnerAccountRepository interface.
type MockLoanPartnerAccountRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLoanPartnerAccountRepositoryMockRecorder
	isgomock struct{}
}

// MockLoanPartnerAccountRepositoryMockRecorder is the mock recorder for MockLoanPartnerAccountRepository.
type MockLoanPartnerAccountRepositoryMockRecorder struct {
	mock *MockLoanPartnerAccountRepository
}

// NewMockLoanPartnerAccountRepository creates a new mock instance.
func NewMockLoanPartnerAccountRepository(ctrl *gomock.Controller) *MockLoanPartnerAccountRepository {
	mock := &MockLoanPartnerAccountRepository{ctrl: ctrl}
	mock.recorder = &MockLoanPartnerAccountRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoanPartnerAccountRepository) EXPECT() *MockLoanPartnerAccountRepositoryMockRecorder {
	return m.recorder
}

// BulkInsertLoanPartnerAccount mocks base method.
func (m *MockLoanPartnerAccountRepository) BulkInsertLoanPartnerAccount(ctx context.Context, in []models.LoanPartnerAccount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkInsertLoanPartnerAccount", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkInsertLoanPartnerAccount indicates an expected call of BulkInsertLoanPartnerAccount.
func (mr *MockLoanPartnerAccountRepositoryMockRecorder) BulkInsertLoanPartnerAccount(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkInsertLoanPartnerAccount", reflect.TypeOf((*MockLoanPartnerAccountRepository)(nil).BulkInsertLoanPartnerAccount), ctx, in)
}

// Create mocks base method.
func (m *MockLoanPartnerAccountRepository) Create(ctx context.Context, in models.LoanPartnerAccount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockLoanPartnerAccountRepositoryMockRecorder) Create(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLoanPartnerAccountRepository)(nil).Create), ctx, in)
}

// GetByParams mocks base method.
func (m *MockLoanPartnerAccountRepository) GetByParams(ctx context.Context, in models.GetLoanPartnerAccountByParamsIn) ([]models.LoanPartnerAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByParams", ctx, in)
	ret0, _ := ret[0].([]models.LoanPartnerAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByParams indicates an expected call of GetByParams.
func (mr *MockLoanPartnerAccountRepositoryMockRecorder) GetByParams(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByParams", reflect.TypeOf((*MockLoanPartnerAccountRepository)(nil).GetByParams), ctx, in)
}

// Update mocks base method.
func (m *MockLoanPartnerAccountRepository) Update(ctx context.Context, in models.UpdateLoanPartnerAccount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockLoanPartnerAccountRepositoryMockRecorder) Update(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockLoanPartnerAccountRepository)(nil).Update), ctx, in)
}
