// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repositories/mysql/mysql_trial_balance.go
//
// Generated by this command:
//
//	mockgen -source=./internal/repositories/mysql/mysql_trial_balance.go -destination=./internal/repositories/mysql/mock/mysql_trial_balance_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "bitbucket.org/Amartha/go-accounting/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockTrialBalanceRepository is a mock of TrialBalanceRepository interface.
type MockTrialBalanceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTrialBalanceRepositoryMockRecorder
	isgomock struct{}
}

// MockTrialBalanceRepositoryMockRecorder is the mock recorder for MockTrialBalanceRepository.
type MockTrialBalanceRepositoryMockRecorder struct {
	mock *MockTrialBalanceRepository
}

// NewMockTrialBalanceRepository creates a new mock instance.
func NewMockTrialBalanceRepository(ctrl *gomock.Controller) *MockTrialBalanceRepository {
	mock := &MockTrialBalanceRepository{ctrl: ctrl}
	mock.recorder = &MockTrialBalanceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrialBalanceRepository) EXPECT() *MockTrialBalanceRepositoryMockRecorder {
	return m.recorder
}

// BulkInsert mocks base method.
func (m *MockTrialBalanceRepository) BulkInsert(ctx context.Context, in []models.CreateTrialBalancePeriod) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkInsert", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkInsert indicates an expected call of BulkInsert.
func (mr *MockTrialBalanceRepositoryMockRecorder) BulkInsert(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkInsert", reflect.TypeOf((*MockTrialBalanceRepository)(nil).BulkInsert), ctx, in)
}

// Close mocks base method.
func (m *MockTrialBalanceRepository) Close(ctx context.Context, in models.CloseTrialBalanceRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockTrialBalanceRepositoryMockRecorder) Close(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockTrialBalanceRepository)(nil).Close), ctx, in)
}

// GetByPeriod mocks base method.
func (m *MockTrialBalanceRepository) GetByPeriod(ctx context.Context, period, entity_code string) (*models.TrialBalancePeriod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPeriod", ctx, period, entity_code)
	ret0, _ := ret[0].(*models.TrialBalancePeriod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPeriod indicates an expected call of GetByPeriod.
func (mr *MockTrialBalanceRepositoryMockRecorder) GetByPeriod(ctx, period, entity_code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPeriod", reflect.TypeOf((*MockTrialBalanceRepository)(nil).GetByPeriod), ctx, period, entity_code)
}

// GetByPeriodStatus mocks base method.
func (m *MockTrialBalanceRepository) GetByPeriodStatus(ctx context.Context, period, status string) ([]models.TrialBalancePeriod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPeriodStatus", ctx, period, status)
	ret0, _ := ret[0].([]models.TrialBalancePeriod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPeriodStatus indicates an expected call of GetByPeriodStatus.
func (mr *MockTrialBalanceRepositoryMockRecorder) GetByPeriodStatus(ctx, period, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPeriodStatus", reflect.TypeOf((*MockTrialBalanceRepository)(nil).GetByPeriodStatus), ctx, period, status)
}

// GetFirstPeriodByStatus mocks base method.
func (m *MockTrialBalanceRepository) GetFirstPeriodByStatus(ctx context.Context, status string) (*models.TrialBalancePeriod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFirstPeriodByStatus", ctx, status)
	ret0, _ := ret[0].(*models.TrialBalancePeriod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFirstPeriodByStatus indicates an expected call of GetFirstPeriodByStatus.
func (mr *MockTrialBalanceRepositoryMockRecorder) GetFirstPeriodByStatus(ctx, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFirstPeriodByStatus", reflect.TypeOf((*MockTrialBalanceRepository)(nil).GetFirstPeriodByStatus), ctx, status)
}

// UpdateTrialBalanceAdjustment mocks base method.
func (m *MockTrialBalanceRepository) UpdateTrialBalanceAdjustment(ctx context.Context, in models.CloseTrialBalanceRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTrialBalanceAdjustment", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTrialBalanceAdjustment indicates an expected call of UpdateTrialBalanceAdjustment.
func (mr *MockTrialBalanceRepositoryMockRecorder) UpdateTrialBalanceAdjustment(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTrialBalanceAdjustment", reflect.TypeOf((*MockTrialBalanceRepository)(nil).UpdateTrialBalanceAdjustment), ctx, in)
}
