// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repositories/mysql/mysql_accounting.go
//
// Generated by this command:
//
//	mockgen -source=./internal/repositories/mysql/mysql_accounting.go -destination=./internal/repositories/mysql/mock/mysql_accounting_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	models "bitbucket.org/Amartha/go-accounting/internal/models"
	decimal "github.com/shopspring/decimal"
	gomock "go.uber.org/mock/gomock"
)

// MockAccountingRepository is a mock of AccountingRepository interface.
type MockAccountingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAccountingRepositoryMockRecorder
	isgomock struct{}
}

// MockAccountingRepositoryMockRecorder is the mock recorder for MockAccountingRepository.
type MockAccountingRepositoryMockRecorder struct {
	mock *MockAccountingRepository
}

// NewMockAccountingRepository creates a new mock instance.
func NewMockAccountingRepository(ctrl *gomock.Controller) *MockAccountingRepository {
	mock := &MockAccountingRepository{ctrl: ctrl}
	mock.recorder = &MockAccountingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountingRepository) EXPECT() *MockAccountingRepositoryMockRecorder {
	return m.recorder
}

// CalculateFromAccountBalanceDaily mocks base method.
func (m *MockAccountingRepository) CalculateFromAccountBalanceDaily(ctx context.Context, in models.CalculateTrialBalance) (models.AccountTrialBalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateFromAccountBalanceDaily", ctx, in)
	ret0, _ := ret[0].(models.AccountTrialBalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CalculateFromAccountBalanceDaily indicates an expected call of CalculateFromAccountBalanceDaily.
func (mr *MockAccountingRepositoryMockRecorder) CalculateFromAccountBalanceDaily(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateFromAccountBalanceDaily", reflect.TypeOf((*MockAccountingRepository)(nil).CalculateFromAccountBalanceDaily), ctx, in)
}

// CalculateFromTransactions mocks base method.
func (m *MockAccountingRepository) CalculateFromTransactions(ctx context.Context, in models.CalculateTrialBalance) (models.AccountTrialBalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateFromTransactions", ctx, in)
	ret0, _ := ret[0].(models.AccountTrialBalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CalculateFromTransactions indicates an expected call of CalculateFromTransactions.
func (mr *MockAccountingRepositoryMockRecorder) CalculateFromTransactions(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateFromTransactions", reflect.TypeOf((*MockAccountingRepository)(nil).CalculateFromTransactions), ctx, in)
}

// CalculateOpeningClosingBalance mocks base method.
func (m *MockAccountingRepository) CalculateOpeningClosingBalance(ctx context.Context, accountNumber string, date time.Time) (models.AccountBalanceDaily, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateOpeningClosingBalance", ctx, accountNumber, date)
	ret0, _ := ret[0].(models.AccountBalanceDaily)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CalculateOpeningClosingBalance indicates an expected call of CalculateOpeningClosingBalance.
func (mr *MockAccountingRepositoryMockRecorder) CalculateOpeningClosingBalance(ctx, accountNumber, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateOpeningClosingBalance", reflect.TypeOf((*MockAccountingRepository)(nil).CalculateOpeningClosingBalance), ctx, accountNumber, date)
}

// CalculateOpeningClosingBalanceFromAccountBalance mocks base method.
func (m *MockAccountingRepository) CalculateOpeningClosingBalanceFromAccountBalance(ctx context.Context, in models.CalculateTrialBalance) (decimal.Decimal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateOpeningClosingBalanceFromAccountBalance", ctx, in)
	ret0, _ := ret[0].(decimal.Decimal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CalculateOpeningClosingBalanceFromAccountBalance indicates an expected call of CalculateOpeningClosingBalanceFromAccountBalance.
func (mr *MockAccountingRepositoryMockRecorder) CalculateOpeningClosingBalanceFromAccountBalance(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateOpeningClosingBalanceFromAccountBalance", reflect.TypeOf((*MockAccountingRepository)(nil).CalculateOpeningClosingBalanceFromAccountBalance), ctx, in)
}

// CheckTransactionIdIsExist mocks base method.
func (m *MockAccountingRepository) CheckTransactionIdIsExist(ctx context.Context, transactionId string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckTransactionIdIsExist", ctx, transactionId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckTransactionIdIsExist indicates an expected call of CheckTransactionIdIsExist.
func (mr *MockAccountingRepositoryMockRecorder) CheckTransactionIdIsExist(ctx, transactionId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckTransactionIdIsExist", reflect.TypeOf((*MockAccountingRepository)(nil).CheckTransactionIdIsExist), ctx, transactionId)
}

// GetAccountBalancePeriodStart mocks base method.
func (m *MockAccountingRepository) GetAccountBalancePeriodStart(ctx context.Context, accountNumber string, date time.Time) (decimal.Decimal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountBalancePeriodStart", ctx, accountNumber, date)
	ret0, _ := ret[0].(decimal.Decimal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountBalancePeriodStart indicates an expected call of GetAccountBalancePeriodStart.
func (mr *MockAccountingRepositoryMockRecorder) GetAccountBalancePeriodStart(ctx, accountNumber, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountBalancePeriodStart", reflect.TypeOf((*MockAccountingRepository)(nil).GetAccountBalancePeriodStart), ctx, accountNumber, date)
}

// GetAccountTransactionByDate mocks base method.
func (m *MockAccountingRepository) GetAccountTransactionByDate(ctx context.Context, entities []string, date time.Time) <-chan models.StreamResult[models.AccountTransation] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountTransactionByDate", ctx, entities, date)
	ret0, _ := ret[0].(<-chan models.StreamResult[models.AccountTransation])
	return ret0
}

// GetAccountTransactionByDate indicates an expected call of GetAccountTransactionByDate.
func (mr *MockAccountingRepositoryMockRecorder) GetAccountTransactionByDate(ctx, entities, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountTransactionByDate", reflect.TypeOf((*MockAccountingRepository)(nil).GetAccountTransactionByDate), ctx, entities, date)
}

// GetAllAccountDailyBalance mocks base method.
func (m *MockAccountingRepository) GetAllAccountDailyBalance(ctx context.Context, entities []string, subCategories *[]models.SubCategory, date time.Time) <-chan models.StreamResult[models.AccountBalanceDaily] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllAccountDailyBalance", ctx, entities, subCategories, date)
	ret0, _ := ret[0].(<-chan models.StreamResult[models.AccountBalanceDaily])
	return ret0
}

// GetAllAccountDailyBalance indicates an expected call of GetAllAccountDailyBalance.
func (mr *MockAccountingRepositoryMockRecorder) GetAllAccountDailyBalance(ctx, entities, subCategories, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllAccountDailyBalance", reflect.TypeOf((*MockAccountingRepository)(nil).GetAllAccountDailyBalance), ctx, entities, subCategories, date)
}

// GetBalanceSheet mocks base method.
func (m *MockAccountingRepository) GetBalanceSheet(ctx context.Context, opts models.BalanceSheetFilterOptions) (models.BalanceSheetOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalanceSheet", ctx, opts)
	ret0, _ := ret[0].(models.BalanceSheetOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalanceSheet indicates an expected call of GetBalanceSheet.
func (mr *MockAccountingRepositoryMockRecorder) GetBalanceSheet(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalanceSheet", reflect.TypeOf((*MockAccountingRepository)(nil).GetBalanceSheet), ctx, opts)
}

// GetJournalDetailByTransactionId mocks base method.
func (m *MockAccountingRepository) GetJournalDetailByTransactionId(ctx context.Context, transactionId string) ([]models.GetJournalDetailOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJournalDetailByTransactionId", ctx, transactionId)
	ret0, _ := ret[0].([]models.GetJournalDetailOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJournalDetailByTransactionId indicates an expected call of GetJournalDetailByTransactionId.
func (mr *MockAccountingRepositoryMockRecorder) GetJournalDetailByTransactionId(ctx, transactionId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJournalDetailByTransactionId", reflect.TypeOf((*MockAccountingRepository)(nil).GetJournalDetailByTransactionId), ctx, transactionId)
}

// GetLastOpeningBalance mocks base method.
func (m *MockAccountingRepository) GetLastOpeningBalance(ctx context.Context, accountNumber string, date time.Time) (decimal.Decimal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastOpeningBalance", ctx, accountNumber, date)
	ret0, _ := ret[0].(decimal.Decimal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastOpeningBalance indicates an expected call of GetLastOpeningBalance.
func (mr *MockAccountingRepositoryMockRecorder) GetLastOpeningBalance(ctx, accountNumber, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastOpeningBalance", reflect.TypeOf((*MockAccountingRepository)(nil).GetLastOpeningBalance), ctx, accountNumber, date)
}

// GetOneAccountBalanceDaily mocks base method.
func (m *MockAccountingRepository) GetOneAccountBalanceDaily(ctx context.Context, accountNumber string, date time.Time) (models.AccountBalanceDaily, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOneAccountBalanceDaily", ctx, accountNumber, date)
	ret0, _ := ret[0].(models.AccountBalanceDaily)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOneAccountBalanceDaily indicates an expected call of GetOneAccountBalanceDaily.
func (mr *MockAccountingRepositoryMockRecorder) GetOneAccountBalanceDaily(ctx, accountNumber, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOneAccountBalanceDaily", reflect.TypeOf((*MockAccountingRepository)(nil).GetOneAccountBalanceDaily), ctx, accountNumber, date)
}

// GetOneSplitAccount mocks base method.
func (m *MockAccountingRepository) GetOneSplitAccount(ctx context.Context, accountNumber string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOneSplitAccount", ctx, accountNumber)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOneSplitAccount indicates an expected call of GetOneSplitAccount.
func (mr *MockAccountingRepositoryMockRecorder) GetOneSplitAccount(ctx, accountNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOneSplitAccount", reflect.TypeOf((*MockAccountingRepository)(nil).GetOneSplitAccount), ctx, accountNumber)
}

// GetOpeningBalanceByDate mocks base method.
func (m *MockAccountingRepository) GetOpeningBalanceByDate(ctx context.Context, accountNumber string, date time.Time) (decimal.Decimal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOpeningBalanceByDate", ctx, accountNumber, date)
	ret0, _ := ret[0].(decimal.Decimal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOpeningBalanceByDate indicates an expected call of GetOpeningBalanceByDate.
func (mr *MockAccountingRepositoryMockRecorder) GetOpeningBalanceByDate(ctx, accountNumber, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOpeningBalanceByDate", reflect.TypeOf((*MockAccountingRepository)(nil).GetOpeningBalanceByDate), ctx, accountNumber, date)
}

// GetOpeningBalanceFromAccountTrialBalance mocks base method.
func (m *MockAccountingRepository) GetOpeningBalanceFromAccountTrialBalance(ctx context.Context, in models.CalculateTrialBalance) (decimal.Decimal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOpeningBalanceFromAccountTrialBalance", ctx, in)
	ret0, _ := ret[0].(decimal.Decimal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOpeningBalanceFromAccountTrialBalance indicates an expected call of GetOpeningBalanceFromAccountTrialBalance.
func (mr *MockAccountingRepositoryMockRecorder) GetOpeningBalanceFromAccountTrialBalance(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOpeningBalanceFromAccountTrialBalance", reflect.TypeOf((*MockAccountingRepository)(nil).GetOpeningBalanceFromAccountTrialBalance), ctx, in)
}

// GetSubLedger mocks base method.
func (m *MockAccountingRepository) GetSubLedger(ctx context.Context, opts models.SubLedgerFilterOptions) ([]models.GetSubLedgerOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubLedger", ctx, opts)
	ret0, _ := ret[0].([]models.GetSubLedgerOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubLedger indicates an expected call of GetSubLedger.
func (mr *MockAccountingRepositoryMockRecorder) GetSubLedger(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubLedger", reflect.TypeOf((*MockAccountingRepository)(nil).GetSubLedger), ctx, opts)
}

// GetSubLedgerAccountTotalTransaction mocks base method.
func (m *MockAccountingRepository) GetSubLedgerAccountTotalTransaction(ctx context.Context, opts models.SubLedgerAccountsFilterOptions) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubLedgerAccountTotalTransaction", ctx, opts)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubLedgerAccountTotalTransaction indicates an expected call of GetSubLedgerAccountTotalTransaction.
func (mr *MockAccountingRepositoryMockRecorder) GetSubLedgerAccountTotalTransaction(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubLedgerAccountTotalTransaction", reflect.TypeOf((*MockAccountingRepository)(nil).GetSubLedgerAccountTotalTransaction), ctx, opts)
}

// GetSubLedgerAccounts mocks base method.
func (m *MockAccountingRepository) GetSubLedgerAccounts(ctx context.Context, opts models.SubLedgerAccountsFilterOptions) ([]models.GetSubLedgerAccountsOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubLedgerAccounts", ctx, opts)
	ret0, _ := ret[0].([]models.GetSubLedgerAccountsOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubLedgerAccounts indicates an expected call of GetSubLedgerAccounts.
func (mr *MockAccountingRepositoryMockRecorder) GetSubLedgerAccounts(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubLedgerAccounts", reflect.TypeOf((*MockAccountingRepository)(nil).GetSubLedgerAccounts), ctx, opts)
}

// GetSubLedgerAccountsCount mocks base method.
func (m *MockAccountingRepository) GetSubLedgerAccountsCount(ctx context.Context, opts models.SubLedgerAccountsFilterOptions) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubLedgerAccountsCount", ctx, opts)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubLedgerAccountsCount indicates an expected call of GetSubLedgerAccountsCount.
func (mr *MockAccountingRepositoryMockRecorder) GetSubLedgerAccountsCount(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubLedgerAccountsCount", reflect.TypeOf((*MockAccountingRepository)(nil).GetSubLedgerAccountsCount), ctx, opts)
}

// GetSubLedgerCount mocks base method.
func (m *MockAccountingRepository) GetSubLedgerCount(ctx context.Context, opts models.SubLedgerFilterOptions) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubLedgerCount", ctx, opts)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubLedgerCount indicates an expected call of GetSubLedgerCount.
func (mr *MockAccountingRepositoryMockRecorder) GetSubLedgerCount(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubLedgerCount", reflect.TypeOf((*MockAccountingRepository)(nil).GetSubLedgerCount), ctx, opts)
}

// GetSubLedgerStream mocks base method.
func (m *MockAccountingRepository) GetSubLedgerStream(ctx context.Context, opts models.SubLedgerFilterOptions) <-chan models.StreamResult[models.GetSubLedgerOut] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubLedgerStream", ctx, opts)
	ret0, _ := ret[0].(<-chan models.StreamResult[models.GetSubLedgerOut])
	return ret0
}

// GetSubLedgerStream indicates an expected call of GetSubLedgerStream.
func (mr *MockAccountingRepositoryMockRecorder) GetSubLedgerStream(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubLedgerStream", reflect.TypeOf((*MockAccountingRepository)(nil).GetSubLedgerStream), ctx, opts)
}

// GetTransactionsToday mocks base method.
func (m *MockAccountingRepository) GetTransactionsToday(ctx context.Context, transactionDate time.Time) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionsToday", ctx, transactionDate)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionsToday indicates an expected call of GetTransactionsToday.
func (mr *MockAccountingRepositoryMockRecorder) GetTransactionsToday(ctx, transactionDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionsToday", reflect.TypeOf((*MockAccountingRepository)(nil).GetTransactionsToday), ctx, transactionDate)
}

// GetTrialBalance mocks base method.
func (m *MockAccountingRepository) GetTrialBalance(ctx context.Context, opts models.TrialBalanceFilterOptions) (map[string][]models.TBCOACategory, map[models.TBCOACategory][]models.TBSubCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrialBalance", ctx, opts)
	ret0, _ := ret[0].(map[string][]models.TBCOACategory)
	ret1, _ := ret[1].(map[models.TBCOACategory][]models.TBSubCategory)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTrialBalance indicates an expected call of GetTrialBalance.
func (mr *MockAccountingRepositoryMockRecorder) GetTrialBalance(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrialBalance", reflect.TypeOf((*MockAccountingRepository)(nil).GetTrialBalance), ctx, opts)
}

// GetTrialBalanceDetails mocks base method.
func (m *MockAccountingRepository) GetTrialBalanceDetails(ctx context.Context, opts models.TrialBalanceDetailsFilterOptions) ([]models.TrialBalanceDetailOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrialBalanceDetails", ctx, opts)
	ret0, _ := ret[0].([]models.TrialBalanceDetailOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrialBalanceDetails indicates an expected call of GetTrialBalanceDetails.
func (mr *MockAccountingRepositoryMockRecorder) GetTrialBalanceDetails(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrialBalanceDetails", reflect.TypeOf((*MockAccountingRepository)(nil).GetTrialBalanceDetails), ctx, opts)
}

// GetTrialBalanceSubCategory mocks base method.
func (m *MockAccountingRepository) GetTrialBalanceSubCategory(ctx context.Context, opts models.TrialBalanceFilterOptions) (models.TrialBalanceBySubCategoryOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrialBalanceSubCategory", ctx, opts)
	ret0, _ := ret[0].(models.TrialBalanceBySubCategoryOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrialBalanceSubCategory indicates an expected call of GetTrialBalanceSubCategory.
func (mr *MockAccountingRepositoryMockRecorder) GetTrialBalanceSubCategory(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrialBalanceSubCategory", reflect.TypeOf((*MockAccountingRepository)(nil).GetTrialBalanceSubCategory), ctx, opts)
}

// GetTrialBalanceV2 mocks base method.
func (m *MockAccountingRepository) GetTrialBalanceV2(ctx context.Context, opts models.TrialBalanceFilterOptions) (map[string][]models.TBCOACategory, map[models.TBCOACategory][]models.TBSubCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrialBalanceV2", ctx, opts)
	ret0, _ := ret[0].(map[string][]models.TBCOACategory)
	ret1, _ := ret[1].(map[models.TBCOACategory][]models.TBSubCategory)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTrialBalanceV2 indicates an expected call of GetTrialBalanceV2.
func (mr *MockAccountingRepositoryMockRecorder) GetTrialBalanceV2(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrialBalanceV2", reflect.TypeOf((*MockAccountingRepository)(nil).GetTrialBalanceV2), ctx, opts)
}

// InsertAccountBalanceDaily mocks base method.
func (m *MockAccountingRepository) InsertAccountBalanceDaily(ctx context.Context, in []models.AccountBalanceDaily) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertAccountBalanceDaily", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertAccountBalanceDaily indicates an expected call of InsertAccountBalanceDaily.
func (mr *MockAccountingRepositoryMockRecorder) InsertAccountBalanceDaily(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertAccountBalanceDaily", reflect.TypeOf((*MockAccountingRepository)(nil).InsertAccountBalanceDaily), ctx, in)
}

// InsertAccountTrialBalance mocks base method.
func (m *MockAccountingRepository) InsertAccountTrialBalance(ctx context.Context, in []models.AccountTrialBalance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertAccountTrialBalance", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertAccountTrialBalance indicates an expected call of InsertAccountTrialBalance.
func (mr *MockAccountingRepositoryMockRecorder) InsertAccountTrialBalance(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertAccountTrialBalance", reflect.TypeOf((*MockAccountingRepository)(nil).InsertAccountTrialBalance), ctx, in)
}

// InsertJournalDetail mocks base method.
func (m *MockAccountingRepository) InsertJournalDetail(ctx context.Context, in []models.CreateJournalDetail) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertJournalDetail", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertJournalDetail indicates an expected call of InsertJournalDetail.
func (mr *MockAccountingRepositoryMockRecorder) InsertJournalDetail(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertJournalDetail", reflect.TypeOf((*MockAccountingRepository)(nil).InsertJournalDetail), ctx, in)
}

// InsertSplit mocks base method.
func (m *MockAccountingRepository) InsertSplit(ctx context.Context, in []models.CreateSplit) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertSplit", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertSplit indicates an expected call of InsertSplit.
func (mr *MockAccountingRepositoryMockRecorder) InsertSplit(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertSplit", reflect.TypeOf((*MockAccountingRepository)(nil).InsertSplit), ctx, in)
}

// InsertSplitAccount mocks base method.
func (m *MockAccountingRepository) InsertSplitAccount(ctx context.Context, in []models.CreateSplitAccount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertSplitAccount", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertSplitAccount indicates an expected call of InsertSplitAccount.
func (mr *MockAccountingRepositoryMockRecorder) InsertSplitAccount(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertSplitAccount", reflect.TypeOf((*MockAccountingRepository)(nil).InsertSplitAccount), ctx, in)
}

// InsertTransaction mocks base method.
func (m *MockAccountingRepository) InsertTransaction(ctx context.Context, in []models.CreateTransaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertTransaction", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertTransaction indicates an expected call of InsertTransaction.
func (mr *MockAccountingRepositoryMockRecorder) InsertTransaction(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertTransaction", reflect.TypeOf((*MockAccountingRepository)(nil).InsertTransaction), ctx, in)
}

// ToggleForeignKeyChecks mocks base method.
func (m *MockAccountingRepository) ToggleForeignKeyChecks(ctx context.Context, isEnable bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToggleForeignKeyChecks", ctx, isEnable)
	ret0, _ := ret[0].(error)
	return ret0
}

// ToggleForeignKeyChecks indicates an expected call of ToggleForeignKeyChecks.
func (mr *MockAccountingRepositoryMockRecorder) ToggleForeignKeyChecks(ctx, isEnable any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleForeignKeyChecks", reflect.TypeOf((*MockAccountingRepository)(nil).ToggleForeignKeyChecks), ctx, isEnable)
}
