// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repositories/mysql/mysql_account.go
//
// Generated by this command:
//
//	mockgen -source=./internal/repositories/mysql/mysql_account.go -destination=./internal/repositories/mysql/mock/mysql_account_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "bitbucket.org/Amartha/go-accounting/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockAccountRepository is a mock of AccountRepository interface.
type MockAccountRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAccountRepositoryMockRecorder
	isgomock struct{}
}

// MockAccountRepositoryMockRecorder is the mock recorder for MockAccountRepository.
type MockAccountRepositoryMockRecorder struct {
	mock *MockAccountRepository
}

// NewMockAccountRepository creates a new mock instance.
func NewMockAccountRepository(ctrl *gomock.Controller) *MockAccountRepository {
	mock := &MockAccountRepository{ctrl: ctrl}
	mock.recorder = &MockAccountRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountRepository) EXPECT() *MockAccountRepositoryMockRecorder {
	return m.recorder
}

// BulkInsertAccount mocks base method.
func (m *MockAccountRepository) BulkInsertAccount(ctx context.Context, in []models.CreateAccount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkInsertAccount", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkInsertAccount indicates an expected call of BulkInsertAccount.
func (mr *MockAccountRepositoryMockRecorder) BulkInsertAccount(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkInsertAccount", reflect.TypeOf((*MockAccountRepository)(nil).BulkInsertAccount), ctx, in)
}

// BulkInsertAcctAccount mocks base method.
func (m *MockAccountRepository) BulkInsertAcctAccount(ctx context.Context, in []models.CreateAccount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkInsertAcctAccount", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkInsertAcctAccount indicates an expected call of BulkInsertAcctAccount.
func (mr *MockAccountRepositoryMockRecorder) BulkInsertAcctAccount(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkInsertAcctAccount", reflect.TypeOf((*MockAccountRepository)(nil).BulkInsertAcctAccount), ctx, in)
}

// CheckAccountNumberIsExist mocks base method.
func (m *MockAccountRepository) CheckAccountNumberIsExist(ctx context.Context, accountNumber string) (*models.CheckAccountNumberIsExist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAccountNumberIsExist", ctx, accountNumber)
	ret0, _ := ret[0].(*models.CheckAccountNumberIsExist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckAccountNumberIsExist indicates an expected call of CheckAccountNumberIsExist.
func (mr *MockAccountRepositoryMockRecorder) CheckAccountNumberIsExist(ctx, accountNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAccountNumberIsExist", reflect.TypeOf((*MockAccountRepository)(nil).CheckAccountNumberIsExist), ctx, accountNumber)
}

// CheckExistByParam mocks base method.
func (m *MockAccountRepository) CheckExistByParam(ctx context.Context, param models.AccountFilterOptions) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckExistByParam", ctx, param)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckExistByParam indicates an expected call of CheckExistByParam.
func (mr *MockAccountRepositoryMockRecorder) CheckExistByParam(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckExistByParam", reflect.TypeOf((*MockAccountRepository)(nil).CheckExistByParam), ctx, param)
}

// CheckLegacyIdIsExist mocks base method.
func (m *MockAccountRepository) CheckLegacyIdIsExist(ctx context.Context, legacyId string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckLegacyIdIsExist", ctx, legacyId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckLegacyIdIsExist indicates an expected call of CheckLegacyIdIsExist.
func (mr *MockAccountRepositoryMockRecorder) CheckLegacyIdIsExist(ctx, legacyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckLegacyIdIsExist", reflect.TypeOf((*MockAccountRepository)(nil).CheckLegacyIdIsExist), ctx, legacyId)
}

// Create mocks base method.
func (m *MockAccountRepository) Create(ctx context.Context, in models.CreateAccount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAccountRepositoryMockRecorder) Create(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAccountRepository)(nil).Create), ctx, in)
}

// CreateLenderAccount mocks base method.
func (m *MockAccountRepository) CreateLenderAccount(ctx context.Context, in models.CreateLenderAccount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLenderAccount", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateLenderAccount indicates an expected call of CreateLenderAccount.
func (mr *MockAccountRepositoryMockRecorder) CreateLenderAccount(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLenderAccount", reflect.TypeOf((*MockAccountRepository)(nil).CreateLenderAccount), ctx, in)
}

// CreateLoanAccount mocks base method.
func (m *MockAccountRepository) CreateLoanAccount(ctx context.Context, in models.CreateLoanAccount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLoanAccount", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateLoanAccount indicates an expected call of CreateLoanAccount.
func (mr *MockAccountRepositoryMockRecorder) CreateLoanAccount(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLoanAccount", reflect.TypeOf((*MockAccountRepository)(nil).CreateLoanAccount), ctx, in)
}

// GetAccountList mocks base method.
func (m *MockAccountRepository) GetAccountList(ctx context.Context, opts models.AccountFilterOptions) ([]models.GetAccountOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountList", ctx, opts)
	ret0, _ := ret[0].([]models.GetAccountOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountList indicates an expected call of GetAccountList.
func (mr *MockAccountRepositoryMockRecorder) GetAccountList(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountList", reflect.TypeOf((*MockAccountRepository)(nil).GetAccountList), ctx, opts)
}

// GetAccountListCount mocks base method.
func (m *MockAccountRepository) GetAccountListCount(ctx context.Context, opts models.AccountFilterOptions) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountListCount", ctx, opts)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountListCount indicates an expected call of GetAccountListCount.
func (mr *MockAccountRepositoryMockRecorder) GetAccountListCount(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountListCount", reflect.TypeOf((*MockAccountRepository)(nil).GetAccountListCount), ctx, opts)
}

// GetAccountNumberByLegacyId mocks base method.
func (m *MockAccountRepository) GetAccountNumberByLegacyId(ctx context.Context, t24AccountNumber string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountNumberByLegacyId", ctx, t24AccountNumber)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountNumberByLegacyId indicates an expected call of GetAccountNumberByLegacyId.
func (mr *MockAccountRepositoryMockRecorder) GetAccountNumberByLegacyId(ctx, t24AccountNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountNumberByLegacyId", reflect.TypeOf((*MockAccountRepository)(nil).GetAccountNumberByLegacyId), ctx, t24AccountNumber)
}

// GetAllAccountNumber mocks base method.
func (m *MockAccountRepository) GetAllAccountNumber(ctx context.Context, entities []string, subCategories *[]models.SubCategory) <-chan models.StreamResult[models.GetAccountOut] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllAccountNumber", ctx, entities, subCategories)
	ret0, _ := ret[0].(<-chan models.StreamResult[models.GetAccountOut])
	return ret0
}

// GetAllAccountNumber indicates an expected call of GetAllAccountNumber.
func (mr *MockAccountRepositoryMockRecorder) GetAllAccountNumber(ctx, entities, subCategories any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllAccountNumber", reflect.TypeOf((*MockAccountRepository)(nil).GetAllAccountNumber), ctx, entities, subCategories)
}

// GetAllAccountNumbersByParam mocks base method.
func (m *MockAccountRepository) GetAllAccountNumbersByParam(ctx context.Context, params models.GetAllAccountNumbersByParamIn) ([]models.GetAllAccountNumbersByParamOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllAccountNumbersByParam", ctx, params)
	ret0, _ := ret[0].([]models.GetAllAccountNumbersByParamOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllAccountNumbersByParam indicates an expected call of GetAllAccountNumbersByParam.
func (mr *MockAccountRepositoryMockRecorder) GetAllAccountNumbersByParam(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllAccountNumbersByParam", reflect.TypeOf((*MockAccountRepository)(nil).GetAllAccountNumbersByParam), ctx, params)
}

// GetLenderAccountByCIHAccountNumber mocks base method.
func (m *MockAccountRepository) GetLenderAccountByCIHAccountNumber(ctx context.Context, accountNumber string) (models.AccountLender, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLenderAccountByCIHAccountNumber", ctx, accountNumber)
	ret0, _ := ret[0].(models.AccountLender)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLenderAccountByCIHAccountNumber indicates an expected call of GetLenderAccountByCIHAccountNumber.
func (mr *MockAccountRepositoryMockRecorder) GetLenderAccountByCIHAccountNumber(ctx, accountNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLenderAccountByCIHAccountNumber", reflect.TypeOf((*MockAccountRepository)(nil).GetLenderAccountByCIHAccountNumber), ctx, accountNumber)
}

// GetLoanAdvanceAccountByLoanAccount mocks base method.
func (m *MockAccountRepository) GetLoanAdvanceAccountByLoanAccount(ctx context.Context, loanAccountNumber string) (models.AccountLoan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoanAdvanceAccountByLoanAccount", ctx, loanAccountNumber)
	ret0, _ := ret[0].(models.AccountLoan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLoanAdvanceAccountByLoanAccount indicates an expected call of GetLoanAdvanceAccountByLoanAccount.
func (mr *MockAccountRepositoryMockRecorder) GetLoanAdvanceAccountByLoanAccount(ctx, loanAccountNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoanAdvanceAccountByLoanAccount", reflect.TypeOf((*MockAccountRepository)(nil).GetLoanAdvanceAccountByLoanAccount), ctx, loanAccountNumber)
}

// GetOneByAccountNumber mocks base method.
func (m *MockAccountRepository) GetOneByAccountNumber(ctx context.Context, accountNumber string) (models.GetAccountOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOneByAccountNumber", ctx, accountNumber)
	ret0, _ := ret[0].(models.GetAccountOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOneByAccountNumber indicates an expected call of GetOneByAccountNumber.
func (mr *MockAccountRepositoryMockRecorder) GetOneByAccountNumber(ctx, accountNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOneByAccountNumber", reflect.TypeOf((*MockAccountRepository)(nil).GetOneByAccountNumber), ctx, accountNumber)
}

// GetOneByLegacyID mocks base method.
func (m *MockAccountRepository) GetOneByLegacyID(ctx context.Context, legacyID string) (models.GetAccountOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOneByLegacyID", ctx, legacyID)
	ret0, _ := ret[0].(models.GetAccountOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOneByLegacyID indicates an expected call of GetOneByLegacyID.
func (mr *MockAccountRepositoryMockRecorder) GetOneByLegacyID(ctx, legacyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOneByLegacyID", reflect.TypeOf((*MockAccountRepository)(nil).GetOneByLegacyID), ctx, legacyID)
}

// Update mocks base method.
func (m *MockAccountRepository) Update(ctx context.Context, in models.UpdateAccount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAccountRepositoryMockRecorder) Update(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAccountRepository)(nil).Update), ctx, in)
}

// UpdateAltId mocks base method.
func (m *MockAccountRepository) UpdateAltId(ctx context.Context, in models.UpdateAltId) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAltId", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAltId indicates an expected call of UpdateAltId.
func (mr *MockAccountRepositoryMockRecorder) UpdateAltId(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAltId", reflect.TypeOf((*MockAccountRepository)(nil).UpdateAltId), ctx, in)
}

// UpdateBySubCategory mocks base method.
func (m *MockAccountRepository) UpdateBySubCategory(ctx context.Context, in models.UpdateBySubCategory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBySubCategory", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBySubCategory indicates an expected call of UpdateBySubCategory.
func (mr *MockAccountRepositoryMockRecorder) UpdateBySubCategory(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBySubCategory", reflect.TypeOf((*MockAccountRepository)(nil).UpdateBySubCategory), ctx, in)
}

// UpdateEntity mocks base method.
func (m *MockAccountRepository) UpdateEntity(ctx context.Context, in models.UpdateAccountEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEntity", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEntity indicates an expected call of UpdateEntity.
func (mr *MockAccountRepositoryMockRecorder) UpdateEntity(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEntity", reflect.TypeOf((*MockAccountRepository)(nil).UpdateEntity), ctx, in)
}

// UpdateLegacyId mocks base method.
func (m *MockAccountRepository) UpdateLegacyId(ctx context.Context, in models.UpdateLegacyId) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLegacyId", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLegacyId indicates an expected call of UpdateLegacyId.
func (mr *MockAccountRepositoryMockRecorder) UpdateLegacyId(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLegacyId", reflect.TypeOf((*MockAccountRepository)(nil).UpdateLegacyId), ctx, in)
}
