// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repositories/mysql/mysql_product_type.go
//
// Generated by this command:
//
//	mockgen -source=./internal/repositories/mysql/mysql_product_type.go -destination=./internal/repositories/mysql/mock/mysql_product_type_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "bitbucket.org/Amartha/go-accounting/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockProductTypeRepository is a mock of ProductTypeRepository interface.
type MockProductTypeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProductTypeRepositoryMockRecorder
	isgomock struct{}
}

// MockProductTypeRepositoryMockRecorder is the mock recorder for MockProductTypeRepository.
type MockProductTypeRepositoryMockRecorder struct {
	mock *MockProductTypeRepository
}

// NewMockProductTypeRepository creates a new mock instance.
func NewMockProductTypeRepository(ctrl *gomock.Controller) *MockProductTypeRepository {
	mock := &MockProductTypeRepository{ctrl: ctrl}
	mock.recorder = &MockProductTypeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductTypeRepository) EXPECT() *MockProductTypeRepositoryMockRecorder {
	return m.recorder
}

// CheckProductTypeIsExist mocks base method.
func (m *MockProductTypeRepository) CheckProductTypeIsExist(ctx context.Context, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckProductTypeIsExist", ctx, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckProductTypeIsExist indicates an expected call of CheckProductTypeIsExist.
func (mr *MockProductTypeRepositoryMockRecorder) CheckProductTypeIsExist(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckProductTypeIsExist", reflect.TypeOf((*MockProductTypeRepository)(nil).CheckProductTypeIsExist), ctx, code)
}

// Create mocks base method.
func (m *MockProductTypeRepository) Create(ctx context.Context, in *models.CreateProductTypeRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockProductTypeRepositoryMockRecorder) Create(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProductTypeRepository)(nil).Create), ctx, in)
}

// GetByCode mocks base method.
func (m *MockProductTypeRepository) GetByCode(ctx context.Context, code string) (*models.ProductType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCode", ctx, code)
	ret0, _ := ret[0].(*models.ProductType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCode indicates an expected call of GetByCode.
func (mr *MockProductTypeRepositoryMockRecorder) GetByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCode", reflect.TypeOf((*MockProductTypeRepository)(nil).GetByCode), ctx, code)
}

// GetLatestProductCode mocks base method.
func (m *MockProductTypeRepository) GetLatestProductCode(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestProductCode", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestProductCode indicates an expected call of GetLatestProductCode.
func (mr *MockProductTypeRepositoryMockRecorder) GetLatestProductCode(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestProductCode", reflect.TypeOf((*MockProductTypeRepository)(nil).GetLatestProductCode), ctx)
}

// List mocks base method.
func (m *MockProductTypeRepository) List(ctx context.Context) ([]models.ProductType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]models.ProductType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockProductTypeRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockProductTypeRepository)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockProductTypeRepository) Update(ctx context.Context, in models.UpdateProductType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockProductTypeRepositoryMockRecorder) Update(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProductTypeRepository)(nil).Update), ctx, in)
}
