// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repositories/mysql/mysql_coa_type.go
//
// Generated by this command:
//
//	mockgen -source=./internal/repositories/mysql/mysql_coa_type.go -destination=./internal/repositories/mysql/mock/mysql_coa_type_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "bitbucket.org/Amartha/go-accounting/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockCOATypeRepository is a mock of COATypeRepository interface.
type MockCOATypeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCOATypeRepositoryMockRecorder
	isgomock struct{}
}

// MockCOATypeRepositoryMockRecorder is the mock recorder for MockCOATypeRepository.
type MockCOATypeRepositoryMockRecorder struct {
	mock *MockCOATypeRepository
}

// NewMockCOATypeRepository creates a new mock instance.
func NewMockCOATypeRepository(ctrl *gomock.Controller) *MockCOATypeRepository {
	mock := &MockCOATypeRepository{ctrl: ctrl}
	mock.recorder = &MockCOATypeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCOATypeRepository) EXPECT() *MockCOATypeRepositoryMockRecorder {
	return m.recorder
}

// CheckCOATypeByCode mocks base method.
func (m *MockCOATypeRepository) CheckCOATypeByCode(ctx context.Context, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckCOATypeByCode", ctx, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckCOATypeByCode indicates an expected call of CheckCOATypeByCode.
func (mr *MockCOATypeRepositoryMockRecorder) CheckCOATypeByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckCOATypeByCode", reflect.TypeOf((*MockCOATypeRepository)(nil).CheckCOATypeByCode), ctx, code)
}

// Create mocks base method.
func (m *MockCOATypeRepository) Create(ctx context.Context, in *models.CreateCOATypeIn) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCOATypeRepositoryMockRecorder) Create(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCOATypeRepository)(nil).Create), ctx, in)
}

// GetAll mocks base method.
func (m *MockCOATypeRepository) GetAll(ctx context.Context) ([]models.COAType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]models.COAType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockCOATypeRepositoryMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockCOATypeRepository)(nil).GetAll), ctx)
}

// GetCOATypeByCode mocks base method.
func (m *MockCOATypeRepository) GetCOATypeByCode(ctx context.Context, code string) (*models.COAType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCOATypeByCode", ctx, code)
	ret0, _ := ret[0].(*models.COAType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCOATypeByCode indicates an expected call of GetCOATypeByCode.
func (mr *MockCOATypeRepositoryMockRecorder) GetCOATypeByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCOATypeByCode", reflect.TypeOf((*MockCOATypeRepository)(nil).GetCOATypeByCode), ctx, code)
}

// Update mocks base method.
func (m *MockCOATypeRepository) Update(ctx context.Context, in models.UpdateCOAType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCOATypeRepositoryMockRecorder) Update(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCOATypeRepository)(nil).Update), ctx, in)
}
