// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repositories/mysql/mysql_sub_category.go
//
// Generated by this command:
//
//	mockgen -source=./internal/repositories/mysql/mysql_sub_category.go -destination=./internal/repositories/mysql/mock/mysql_sub_category_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "bitbucket.org/Amartha/go-accounting/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockSubCategoryRepository is a mock of SubCategoryRepository interface.
type MockSubCategoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSubCategoryRepositoryMockRecorder
	isgomock struct{}
}

// MockSubCategoryRepositoryMockRecorder is the mock recorder for MockSubCategoryRepository.
type MockSubCategoryRepositoryMockRecorder struct {
	mock *MockSubCategoryRepository
}

// NewMockSubCategoryRepository creates a new mock instance.
func NewMockSubCategoryRepository(ctrl *gomock.Controller) *MockSubCategoryRepository {
	mock := &MockSubCategoryRepository{ctrl: ctrl}
	mock.recorder = &MockSubCategoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubCategoryRepository) EXPECT() *MockSubCategoryRepositoryMockRecorder {
	return m.recorder
}

// CheckSubCategoryByCodeAndCategoryCode mocks base method.
func (m *MockSubCategoryRepository) CheckSubCategoryByCodeAndCategoryCode(ctx context.Context, code, categoryCode string) (*models.SubCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckSubCategoryByCodeAndCategoryCode", ctx, code, categoryCode)
	ret0, _ := ret[0].(*models.SubCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckSubCategoryByCodeAndCategoryCode indicates an expected call of CheckSubCategoryByCodeAndCategoryCode.
func (mr *MockSubCategoryRepositoryMockRecorder) CheckSubCategoryByCodeAndCategoryCode(ctx, code, categoryCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckSubCategoryByCodeAndCategoryCode", reflect.TypeOf((*MockSubCategoryRepository)(nil).CheckSubCategoryByCodeAndCategoryCode), ctx, code, categoryCode)
}

// Create mocks base method.
func (m *MockSubCategoryRepository) Create(ctx context.Context, in *models.CreateSubCategory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSubCategoryRepositoryMockRecorder) Create(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSubCategoryRepository)(nil).Create), ctx, in)
}

// GetAll mocks base method.
func (m *MockSubCategoryRepository) GetAll(ctx context.Context, param models.GetAllSubCategoryParam) (*[]models.SubCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, param)
	ret0, _ := ret[0].(*[]models.SubCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockSubCategoryRepositoryMockRecorder) GetAll(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockSubCategoryRepository)(nil).GetAll), ctx, param)
}

// GetByAccountType mocks base method.
func (m *MockSubCategoryRepository) GetByAccountType(ctx context.Context, accountType string) (*models.SubCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAccountType", ctx, accountType)
	ret0, _ := ret[0].(*models.SubCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAccountType indicates an expected call of GetByAccountType.
func (mr *MockSubCategoryRepositoryMockRecorder) GetByAccountType(ctx, accountType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAccountType", reflect.TypeOf((*MockSubCategoryRepository)(nil).GetByAccountType), ctx, accountType)
}

// GetByCode mocks base method.
func (m *MockSubCategoryRepository) GetByCode(ctx context.Context, code string) (*models.SubCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCode", ctx, code)
	ret0, _ := ret[0].(*models.SubCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCode indicates an expected call of GetByCode.
func (mr *MockSubCategoryRepositoryMockRecorder) GetByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCode", reflect.TypeOf((*MockSubCategoryRepository)(nil).GetByCode), ctx, code)
}

// GetLatestSubCategCode mocks base method.
func (m *MockSubCategoryRepository) GetLatestSubCategCode(ctx context.Context, categCode string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestSubCategCode", ctx, categCode)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestSubCategCode indicates an expected call of GetLatestSubCategCode.
func (mr *MockSubCategoryRepositoryMockRecorder) GetLatestSubCategCode(ctx, categCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestSubCategCode", reflect.TypeOf((*MockSubCategoryRepository)(nil).GetLatestSubCategCode), ctx, categCode)
}

// Update mocks base method.
func (m *MockSubCategoryRepository) Update(ctx context.Context, in models.UpdateSubCategory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSubCategoryRepositoryMockRecorder) Update(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSubCategoryRepository)(nil).Update), ctx, in)
}
