// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repositories/mysql/mysql_entity.go
//
// Generated by this command:
//
//	mockgen -source=./internal/repositories/mysql/mysql_entity.go -destination=./internal/repositories/mysql/mock/mysql_entity_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "bitbucket.org/Amartha/go-accounting/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockEntityRepository is a mock of EntityRepository interface.
type MockEntityRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEntityRepositoryMockRecorder
	isgomock struct{}
}

// MockEntityRepositoryMockRecorder is the mock recorder for MockEntityRepository.
type MockEntityRepositoryMockRecorder struct {
	mock *MockEntityRepository
}

// NewMockEntityRepository creates a new mock instance.
func NewMockEntityRepository(ctrl *gomock.Controller) *MockEntityRepository {
	mock := &MockEntityRepository{ctrl: ctrl}
	mock.recorder = &MockEntityRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEntityRepository) EXPECT() *MockEntityRepositoryMockRecorder {
	return m.recorder
}

// CheckEntityByCode mocks base method.
func (m *MockEntityRepository) CheckEntityByCode(ctx context.Context, code, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckEntityByCode", ctx, code, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckEntityByCode indicates an expected call of CheckEntityByCode.
func (mr *MockEntityRepositoryMockRecorder) CheckEntityByCode(ctx, code, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckEntityByCode", reflect.TypeOf((*MockEntityRepository)(nil).CheckEntityByCode), ctx, code, status)
}

// Create mocks base method.
func (m *MockEntityRepository) Create(ctx context.Context, in *models.CreateEntityIn) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockEntityRepositoryMockRecorder) Create(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEntityRepository)(nil).Create), ctx, in)
}

// GetByCode mocks base method.
func (m *MockEntityRepository) GetByCode(ctx context.Context, code string) (*models.Entity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCode", ctx, code)
	ret0, _ := ret[0].(*models.Entity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCode indicates an expected call of GetByCode.
func (mr *MockEntityRepositoryMockRecorder) GetByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCode", reflect.TypeOf((*MockEntityRepository)(nil).GetByCode), ctx, code)
}

// GetByParams mocks base method.
func (m *MockEntityRepository) GetByParams(ctx context.Context, in models.GetEntity) (*models.Entity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByParams", ctx, in)
	ret0, _ := ret[0].(*models.Entity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByParams indicates an expected call of GetByParams.
func (mr *MockEntityRepositoryMockRecorder) GetByParams(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByParams", reflect.TypeOf((*MockEntityRepository)(nil).GetByParams), ctx, in)
}

// List mocks base method.
func (m *MockEntityRepository) List(ctx context.Context) (*[]models.Entity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].(*[]models.Entity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockEntityRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockEntityRepository)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockEntityRepository) Update(ctx context.Context, in models.UpdateEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockEntityRepositoryMockRecorder) Update(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockEntityRepository)(nil).Update), ctx, in)
}
