// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/pkg/goigate/client.go
//
// Generated by this command:
//
//	mockgen -source=./internal/pkg/goigate/client.go -destination=./internal/pkg/goigate/mock/client_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	igate "bitbucket.org/Amartha/go-igate"
	gomock "go.uber.org/mock/gomock"
)

// MockIgateClient is a mock of IgateClient interface.
type MockIgateClient struct {
	ctrl     *gomock.Controller
	recorder *MockIgateClientMockRecorder
	isgomock struct{}
}

// MockIgateClientMockRecorder is the mock recorder for MockIgateClient.
type MockIgateClientMockRecorder struct {
	mock *MockIgateClient
}

// NewMockIgateClient creates a new mock instance.
func NewMockIgateClient(ctrl *gomock.Controller) *MockIgateClient {
	mock := &MockIgateClient{ctrl: ctrl}
	mock.recorder = &MockIgateClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIgateClient) EXPECT() *MockIgateClientMockRecorder {
	return m.recorder
}

// CreateCorporateLenderAccount mocks base method.
func (m *MockIgateClient) CreateCorporateLenderAccount(ctx context.Context, in igate.CorporateLenderAccountRequest) (*igate.CorporateLenderAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCorporateLenderAccount", ctx, in)
	ret0, _ := ret[0].(*igate.CorporateLenderAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCorporateLenderAccount indicates an expected call of CreateCorporateLenderAccount.
func (mr *MockIgateClientMockRecorder) CreateCorporateLenderAccount(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCorporateLenderAccount", reflect.TypeOf((*MockIgateClient)(nil).CreateCorporateLenderAccount), ctx, in)
}

// CreateLenderAccountNonRDL mocks base method.
func (m *MockIgateClient) CreateLenderAccountNonRDL(ctx context.Context, in igate.LenderAccountRequest) (*igate.LenderAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLenderAccountNonRDL", ctx, in)
	ret0, _ := ret[0].(*igate.LenderAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLenderAccountNonRDL indicates an expected call of CreateLenderAccountNonRDL.
func (mr *MockIgateClientMockRecorder) CreateLenderAccountNonRDL(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLenderAccountNonRDL", reflect.TypeOf((*MockIgateClient)(nil).CreateLenderAccountNonRDL), ctx, in)
}

// GetAccountIA mocks base method.
func (m *MockIgateClient) GetAccountIA(ctx context.Context, opts igate.GetAccountIAOptions) ([]*igate.CoreResGetAccountIA, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountIA", ctx, opts)
	ret0, _ := ret[0].([]*igate.CoreResGetAccountIA)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountIA indicates an expected call of GetAccountIA.
func (mr *MockIgateClientMockRecorder) GetAccountIA(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountIA", reflect.TypeOf((*MockIgateClient)(nil).GetAccountIA), ctx, opts)
}

// GetLender mocks base method.
func (m *MockIgateClient) GetLender(ctx context.Context, opts igate.CustomerGetLenderOptions) (*igate.Lender, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLender", ctx, opts)
	ret0, _ := ret[0].(*igate.Lender)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLender indicates an expected call of GetLender.
func (mr *MockIgateClientMockRecorder) GetLender(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLender", reflect.TypeOf((*MockIgateClient)(nil).GetLender), ctx, opts)
}

// GetLoanAccount mocks base method.
func (m *MockIgateClient) GetLoanAccount(ctx context.Context, opts igate.LoanAccountGetOptions) (*igate.LoanAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoanAccount", ctx, opts)
	ret0, _ := ret[0].(*igate.LoanAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLoanAccount indicates an expected call of GetLoanAccount.
func (mr *MockIgateClientMockRecorder) GetLoanAccount(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoanAccount", reflect.TypeOf((*MockIgateClient)(nil).GetLoanAccount), ctx, opts)
}

// RegisterSavingAccount mocks base method.
func (m *MockIgateClient) RegisterSavingAccount(ctx context.Context, in igate.GeneralSavingAccountRequest) (*igate.GeneralSavingAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterSavingAccount", ctx, in)
	ret0, _ := ret[0].(*igate.GeneralSavingAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterSavingAccount indicates an expected call of RegisterSavingAccount.
func (mr *MockIgateClientMockRecorder) RegisterSavingAccount(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterSavingAccount", reflect.TypeOf((*MockIgateClient)(nil).RegisterSavingAccount), ctx, in)
}
