// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/pkg/dddnotification/client.go
//
// Generated by this command:
//
//	mockgen -source=./internal/pkg/dddnotification/client.go -destination=./internal/pkg/dddnotification/mock/client_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	dddnotification "bitbucket.org/Amartha/go-accounting/internal/pkg/dddnotification"
	gomock "go.uber.org/mock/gomock"
)

// MockDDDNotificationClient is a mock of DDDNotificationClient interface.
type MockDDDNotificationClient struct {
	ctrl     *gomock.Controller
	recorder *MockDDDNotificationClientMockRecorder
	isgomock struct{}
}

// MockDDDNotificationClientMockRecorder is the mock recorder for MockDDDNotificationClient.
type MockDDDNotificationClientMockRecorder struct {
	mock *MockDDDNotificationClient
}

// NewMockDDDNotificationClient creates a new mock instance.
func NewMockDDDNotificationClient(ctrl *gomock.Controller) *MockDDDNotificationClient {
	mock := &MockDDDNotificationClient{ctrl: ctrl}
	mock.recorder = &MockDDDNotificationClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDDDNotificationClient) EXPECT() *MockDDDNotificationClientMockRecorder {
	return m.recorder
}

// SendEmail mocks base method.
func (m *MockDDDNotificationClient) SendEmail(ctx context.Context, request dddnotification.RequestEmail) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEmail", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendEmail indicates an expected call of SendEmail.
func (mr *MockDDDNotificationClientMockRecorder) SendEmail(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmail", reflect.TypeOf((*MockDDDNotificationClient)(nil).SendEmail), ctx, request)
}

// SendMessageToSlack mocks base method.
func (m *MockDDDNotificationClient) SendMessageToSlack(ctx context.Context, message dddnotification.MessageData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessageToSlack", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessageToSlack indicates an expected call of SendMessageToSlack.
func (mr *MockDDDNotificationClientMockRecorder) SendMessageToSlack(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessageToSlack", reflect.TypeOf((*MockDDDNotificationClient)(nil).SendMessageToSlack), ctx, message)
}
