// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/pkg/flag/flag.go
//
// Generated by this command:
//
//	mockgen -source=./internal/pkg/flag/flag.go -destination=./internal/pkg/flag/mock/flag_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	flag "bitbucket.org/Amartha/go-feature-flag-sdk"
	api "github.com/Unleash/unleash-client-go/v3/api"
	gomock "go.uber.org/mock/gomock"
)

// MockFlaggerClient is a mock of FlaggerClient interface.
type MockFlaggerClient struct {
	ctrl     *gomock.Controller
	recorder *MockFlaggerClientMockRecorder
	isgomock struct{}
}

// MockFlaggerClientMockRecorder is the mock recorder for MockFlaggerClient.
type MockFlaggerClientMockRecorder struct {
	mock *MockFlaggerClient
}

// NewMockFlaggerClient creates a new mock instance.
func NewMockFlaggerClient(ctrl *gomock.Controller) *MockFlaggerClient {
	mock := &MockFlaggerClient{ctrl: ctrl}
	mock.recorder = &MockFlaggerClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlaggerClient) EXPECT() *MockFlaggerClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockFlaggerClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockFlaggerClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockFlaggerClient)(nil).Close))
}

// GetVariant mocks base method.
func (m *MockFlaggerClient) GetVariant(name string) *api.Variant {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVariant", name)
	ret0, _ := ret[0].(*api.Variant)
	return ret0
}

// GetVariant indicates an expected call of GetVariant.
func (mr *MockFlaggerClientMockRecorder) GetVariant(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVariant", reflect.TypeOf((*MockFlaggerClient)(nil).GetVariant), name)
}

// IsEnabled mocks base method.
func (m *MockFlaggerClient) IsEnabled(arg0 string, arg1 ...flag.FeatureOption) bool {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "IsEnabled", varargs...)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsEnabled indicates an expected call of IsEnabled.
func (mr *MockFlaggerClientMockRecorder) IsEnabled(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEnabled", reflect.TypeOf((*MockFlaggerClient)(nil).IsEnabled), varargs...)
}

// WaitForReady mocks base method.
func (m *MockFlaggerClient) WaitForReady() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WaitForReady")
}

// WaitForReady indicates an expected call of WaitForReady.
func (mr *MockFlaggerClientMockRecorder) WaitForReady() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForReady", reflect.TypeOf((*MockFlaggerClient)(nil).WaitForReady))
}
