// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/pkg/godbledger/godbledger.go
//
// Generated by this command:
//
//	mockgen -source=./internal/pkg/godbledger/godbledger.go -destination=./internal/pkg/godbledger/mock/godbledger_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	godbledger "bitbucket.org/Amartha/go-accounting/internal/pkg/godbledger"
	core "github.com/darcys22/godbledger/godbledger/core"
	gomock "go.uber.org/mock/gomock"
)

// MockGoDBLedger is a mock of GoDBLedger interface.
type MockGoDBLedger struct {
	ctrl     *gomock.Controller
	recorder *MockGoDBLedgerMockRecorder
	isgomock struct{}
}

// MockGoDBLedgerMockRecorder is the mock recorder for MockGoDBLedger.
type MockGoDBLedgerMockRecorder struct {
	mock *MockGoDBLedger
}

// NewMockGoDBLedger creates a new mock instance.
func NewMockGoDBLedger(ctrl *gomock.Controller) *MockGoDBLedger {
	mock := &MockGoDBLedger{ctrl: ctrl}
	mock.recorder = &MockGoDBLedgerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGoDBLedger) EXPECT() *MockGoDBLedgerMockRecorder {
	return m.recorder
}

// FindTransaction mocks base method.
func (m *MockGoDBLedger) FindTransaction(ctx context.Context, txnID string) (*core.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTransaction", ctx, txnID)
	ret0, _ := ret[0].(*core.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTransaction indicates an expected call of FindTransaction.
func (mr *MockGoDBLedgerMockRecorder) FindTransaction(ctx, txnID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTransaction", reflect.TypeOf((*MockGoDBLedger)(nil).FindTransaction), ctx, txnID)
}

// GetAccount mocks base method.
func (m *MockGoDBLedger) GetAccount(ctx context.Context, code string) (*core.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccount", ctx, code)
	ret0, _ := ret[0].(*core.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccount indicates an expected call of GetAccount.
func (mr *MockGoDBLedgerMockRecorder) GetAccount(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccount", reflect.TypeOf((*MockGoDBLedger)(nil).GetAccount), ctx, code)
}

// GetCurrency mocks base method.
func (m *MockGoDBLedger) GetCurrency(ctx context.Context, currency string) (godbledger.Currency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrency", ctx, currency)
	ret0, _ := ret[0].(godbledger.Currency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrency indicates an expected call of GetCurrency.
func (mr *MockGoDBLedgerMockRecorder) GetCurrency(ctx, currency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrency", reflect.TypeOf((*MockGoDBLedger)(nil).GetCurrency), ctx, currency)
}

// InsertAccount mocks base method.
func (m *MockGoDBLedger) InsertAccount(ctx context.Context, accountID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertAccount", ctx, accountID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertAccount indicates an expected call of InsertAccount.
func (mr *MockGoDBLedgerMockRecorder) InsertAccount(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertAccount", reflect.TypeOf((*MockGoDBLedger)(nil).InsertAccount), ctx, accountID)
}

// InsertTransaction mocks base method.
func (m *MockGoDBLedger) InsertTransaction(ctx context.Context, txn godbledger.Transaction) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertTransaction", ctx, txn)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertTransaction indicates an expected call of InsertTransaction.
func (mr *MockGoDBLedgerMockRecorder) InsertTransaction(ctx, txn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertTransaction", reflect.TypeOf((*MockGoDBLedger)(nil).InsertTransaction), ctx, txn)
}
