// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repositories/storage/storage.go
//
// Generated by this command:
//
//	mockgen -source=./internal/repositories/storage/storage.go -destination=./internal/repositories/storage/mock/storage_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "bitbucket.org/Amartha/go-accounting/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockStorageRepository is a mock of StorageRepository interface.
type MockStorageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStorageRepositoryMockRecorder
	isgomock struct{}
}

// MockStorageRepositoryMockRecorder is the mock recorder for MockStorageRepository.
type MockStorageRepositoryMockRecorder struct {
	mock *MockStorageRepository
}

// NewMockStorageRepository creates a new mock instance.
func NewMockStorageRepository(ctrl *gomock.Controller) *MockStorageRepository {
	mock := &MockStorageRepository{ctrl: ctrl}
	mock.recorder = &MockStorageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageRepository) EXPECT() *MockStorageRepositoryMockRecorder {
	return m.recorder
}

// Stream mocks base method.
func (m *MockStorageRepository) Stream(ctx context.Context, bucketName, objectName string) (chan models.StreamResult[string], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stream", ctx, bucketName, objectName)
	ret0, _ := ret[0].(chan models.StreamResult[string])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stream indicates an expected call of Stream.
func (mr *MockStorageRepositoryMockRecorder) Stream(ctx, bucketName, objectName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stream", reflect.TypeOf((*MockStorageRepository)(nil).Stream), ctx, bucketName, objectName)
}
