// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/pkg/acuanclient/client.go
//
// Generated by this command:
//
//	mockgen -source=./internal/pkg/acuanclient/client.go -destination=./internal/pkg/acuanclient/mock/client_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	acuanclient "bitbucket.org/Amartha/go-accounting/internal/pkg/acuanclient"
	gomock "go.uber.org/mock/gomock"
)

// MockAcuanClient is a mock of AcuanClient interface.
type MockAcuanClient struct {
	ctrl     *gomock.Controller
	recorder *MockAcuanClientMockRecorder
	isgomock struct{}
}

// MockAcuanClientMockRecorder is the mock recorder for MockAcuanClient.
type MockAcuanClientMockRecorder struct {
	mock *MockAcuanClient
}

// NewMockAcuanClient creates a new mock instance.
func NewMockAcuanClient(ctrl *gomock.Controller) *MockAcuanClient {
	mock := &MockAcuanClient{ctrl: ctrl}
	mock.recorder = &MockAcuanClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAcuanClient) EXPECT() *MockAcuanClientMockRecorder {
	return m.recorder
}

// PublishAccount mocks base method.
func (m *MockAcuanClient) PublishAccount(ctx context.Context, data acuanclient.PublishAccountData) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PublishAccount", ctx, data)
}

// PublishAccount indicates an expected call of PublishAccount.
func (mr *MockAcuanClientMockRecorder) PublishAccount(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishAccount", reflect.TypeOf((*MockAcuanClient)(nil).PublishAccount), ctx, data)
}
