// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/pkg/queueunicorn/client.go
//
// Generated by this command:
//
//	mockgen -source=./internal/pkg/queueunicorn/client.go -destination=./internal/pkg/queueunicorn/mock/client_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	queueunicorn "bitbucket.org/Amartha/go-accounting/internal/pkg/queueunicorn"
	gomock "go.uber.org/mock/gomock"
)

// MockQueueUnicornClient is a mock of QueueUnicornClient interface.
type MockQueueUnicornClient struct {
	ctrl     *gomock.Controller
	recorder *MockQueueUnicornClientMockRecorder
	isgomock struct{}
}

// MockQueueUnicornClientMockRecorder is the mock recorder for MockQueueUnicornClient.
type MockQueueUnicornClientMockRecorder struct {
	mock *MockQueueUnicornClient
}

// NewMockQueueUnicornClient creates a new mock instance.
func NewMockQueueUnicornClient(ctrl *gomock.Controller) *MockQueueUnicornClient {
	mock := &MockQueueUnicornClient{ctrl: ctrl}
	mock.recorder = &MockQueueUnicornClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueueUnicornClient) EXPECT() *MockQueueUnicornClientMockRecorder {
	return m.recorder
}

// SendJobHTTP mocks base method.
func (m *MockQueueUnicornClient) SendJobHTTP(ctx context.Context, request queueunicorn.RequestJobHTTP) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendJobHTTP", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendJobHTTP indicates an expected call of SendJobHTTP.
func (mr *MockQueueUnicornClientMockRecorder) SendJobHTTP(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendJobHTTP", reflect.TypeOf((*MockQueueUnicornClient)(nil).SendJobHTTP), ctx, request)
}
