// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/pkg/gofptransaction/client.go
//
// Generated by this command:
//
//	mockgen -source=./internal/pkg/gofptransaction/client.go -destination=./internal/pkg/gofptransaction/mock/client_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gofptransaction "bitbucket.org/Amartha/go-accounting/internal/pkg/gofptransaction"
	gomock "go.uber.org/mock/gomock"
)

// MockFpTransactionClient is a mock of FpTransactionClient interface.
type MockFpTransactionClient struct {
	ctrl     *gomock.Controller
	recorder *MockFpTransactionClientMockRecorder
	isgomock struct{}
}

// MockFpTransactionClientMockRecorder is the mock recorder for MockFpTransactionClient.
type MockFpTransactionClientMockRecorder struct {
	mock *MockFpTransactionClient
}

// NewMockFpTransactionClient creates a new mock instance.
func NewMockFpTransactionClient(ctrl *gomock.Controller) *MockFpTransactionClient {
	mock := &MockFpTransactionClient{ctrl: ctrl}
	mock.recorder = &MockFpTransactionClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFpTransactionClient) EXPECT() *MockFpTransactionClientMockRecorder {
	return m.recorder
}

// GetAllOrderTypes mocks base method.
func (m *MockFpTransactionClient) GetAllOrderTypes(ctx context.Context, orderTypeCode, orderTypeName string) (gofptransaction.GetAllOrderTypesOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllOrderTypes", ctx, orderTypeCode, orderTypeName)
	ret0, _ := ret[0].(gofptransaction.GetAllOrderTypesOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllOrderTypes indicates an expected call of GetAllOrderTypes.
func (mr *MockFpTransactionClientMockRecorder) GetAllOrderTypes(ctx, orderTypeCode, orderTypeName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllOrderTypes", reflect.TypeOf((*MockFpTransactionClient)(nil).GetAllOrderTypes), ctx, orderTypeCode, orderTypeName)
}

// UpdateAccountBySubCategory mocks base method.
func (m *MockFpTransactionClient) UpdateAccountBySubCategory(ctx context.Context, in gofptransaction.UpdateBySubCategory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccountBySubCategory", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAccountBySubCategory indicates an expected call of UpdateAccountBySubCategory.
func (mr *MockFpTransactionClientMockRecorder) UpdateAccountBySubCategory(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccountBySubCategory", reflect.TypeOf((*MockFpTransactionClient)(nil).UpdateAccountBySubCategory), ctx, in)
}
